import {
  siAmazonapigateway,
  siAmazoncloudwatch,
  siAmazoncognito,
  siAmazondocumentdb,
  siAmazondynamodb,
  siAmazonec2,
  siAmazonecs,
  siAmazoneks,
  siAmazonelasticache,
  siAmazoniam,
  siAmazonrds,
  siAmazonredshift,
  siAmazonroute53,
  siAmazons3,
  siAmazonsimpleemailservice,
  siAmazonsqs,
  siAmazonwebservices,
  siApachekafka,
  siApachespark,
  siAnthropic,
  siArgo,
  siAwsamplify,
  siAwselasticloadbalancing,
  siAwsfargate,
  siAwslambda,
  siAwsorganizations,
  siAwssecretsmanager,
  siCloudflare,
  siDatabricks,
  siDigitalocean,
  siDocker,
  siGrafana,
  siGooglecloud,
  siHelm,
  siHetzner,
  siHuggingface,
  siJupyter,
  siKeras,
  siKubernetes,
  siLangchain,
  siMlflow,
  siMongodb,
  siNeo4j,
  siNginx,
  siOllama,
  siOpenai,
  siPostgresql,
  siPrometheus,
  siPytorch,
  siRabbitmq,
  siRedis,
  siScaleway,
  siScikitlearn,
  siSnowflake,
  siTerraform,
  siTensorflow,
  siVercel,
} from 'simple-icons';
import {
  siAkamai,
  siAnsible,
  siApachemaven,
  siArtifacthub,
  siBamboo,
  siBitbucket,
  siBitrise,
  siBuddy,
  siBuildkite,
  siCaddy,
  siCheckmk,
  siChef,
  siCircleci,
  siCilium,
  siCodecov,
  siCodefresh,
  siConcourse,
  siConsul,
  siContainerd,
  siCypress,
  siDatadog,
  siDependabot,
  siDrone,
  siDynatrace,
  siElastic,
  siElasticsearch,
  siEnvoyproxy,
  siEslint,
  siF5,
  siFalco,
  siFastlane,
  siFastly,
  siFluentbit,
  siFluentd,
  siFlux,
  siForgejo,
  siFortinet,
  siGitea,
  siGithub,
  siGithubactions,
  siGithubcopilot,
  siGitkraken,
  siGitlab,
  siGitlfs,
  siGitpod,
  siGradle,
  siGraylog,
  siHarbor,
  siIcinga,
  siInsomnia,
  siIstio,
  siJaeger,
  siJenkins,
  siJest,
  siJetbrains,
  siJfrog,
  siJfrogpipelines,
  siJunipernetworks,
  siKibana,
  siKeycdn,
  siLinkerd,
  siMocha,
  siNewrelic,
  siNextdns,
  siNomad,
  siNpm,
  siOctopusdeploy,
  siOpenapiinitiative,
  siOpenvpn,
  siOpentelemetry,
  siOpentofu,
  siOpsgenie,
  siPacker,
  siPagerduty,
  siPaloaltonetworks,
  siPingdom,
  siPnpm,
  siPodman,
  siPortainer,
  siPostman,
  siPrecommit,
  siPrettier,
  siPulumi,
  siPuppet,
  siRancher,
  siRenovate,
  siSaltproject,
  siSelenium,
  siSemaphoreci,
  siSentry,
  siServerless,
  siSonarqube,
  siSonatype,
  siSnyk,
  siSpinnaker,
  siSplunk,
  siStatuspage,
  siSwagger,
  siTeamcity,
  siTailscale,
  siTekton,
  siThanos,
  siTrivy,
  siTravisci,
  siTraefikproxy,
  siUptimekuma,
  siVagrant,
  siVault,
  siVitest,
  siWireguard,
  siXcode,
  siYarn,
  siZerotier,
} from 'simple-icons';
import { SYS_TRAFFIC_FLOW_ICONS } from './sysTrafficFlowIcons.js';

function fromSimple(icon) {
  return {
    kind: 'path',
    title: icon.title,
    hex: icon.hex,
    path: icon.path,
  };
}

/** Official resource artwork: https://github.com/kubernetes/community (Apache-2.0) */
function k8sResource(svgBasename, title) {
  return {
    kind: 'url',
    title,
    hex: '326CE5',
    url: `/icons/k8s/${svgBasename}.svg`,
  };
}

/** PNGs from https://github.com/awslabs/aws-icons-for-plantuml (Apache-2.0) */
const AWS_ARCH_ORANGE = 'FF9900';

function awsArchPng(dir, file) {
  return {
    kind: 'url',
    title: file,
    hex: AWS_ARCH_ORANGE,
    url: `/icons/aws-plantuml/${dir}/${file}.png`,
  };
}

/** @param {string} dir @param {Record<string, string>} keyToFilename */
function mapAwsArch(dir, keyToFilename) {
  const out = {};
  for (const [key, file] of Object.entries(keyToFilename)) {
    out[key] = awsArchPng(dir, file);
  }
  return out;
}

const AWS_AI_MAP = {
  awsai_bedrock: 'Bedrock',
  awsai_bedrock_agent_core: 'BedrockAgentCore',
  awsai_sagemaker: 'SageMakerAI',
  awsai_sagemaker_ground_truth: 'SageMakerGroundTruth',
  awsai_sagemaker_notebook: 'SageMakerAINotebook',
  awsai_comprehend: 'Comprehend',
  awsai_comprehend_medical: 'ComprehendMedical',
  awsai_rekognition: 'Rekognition',
  awsai_textract: 'Textract',
  awsai_lex: 'Lex',
  awsai_polly: 'Polly',
  awsai_transcribe: 'Transcribe',
  awsai_translate: 'Translate',
  awsai_kendra: 'Kendra',
  awsai_personalize: 'Personalize',
  awsai_forecast: 'Forecast',
  awsai_fraud_detector: 'FraudDetector',
  awsai_deep_racer: 'DeepRacer',
  awsai_augmented_ai: 'AugmentedAIA2I',
  awsai_panorama: 'Panorama',
  awsai_codeguru: 'CodeGuru',
  awsai_q: 'Q',
  awsai_nova: 'Nova',
  awsai_elastic_inference: 'ElasticInference',
  awsai_pytorch_on_aws: 'PyTorchonAWS',
  awsai_tensorflow_on_aws: 'TensorFlowonAWS',
  awsai_deep_learning_containers: 'DeepLearningContainers',
  awsai_deep_learning_amis: 'DeepLearningAMIs',
  awsai_devops_guru: 'DevOpsGuru',
  awsai_monitron: 'Monitron',
  awsai_lookout_equipment: 'LookoutforEquipment',
  awsai_lookout_vision: 'LookoutforVision',
  awsai_codewhisperer: 'CodeWhisperer',
  awsai_health_scribe: 'HealthScribe',
  awsai_neuron: 'Neuron',
};

const AWS_ANALYTICS_MAP = {
  awsana_athena: 'Athena',
  awsana_emr: 'EMR',
  awsana_glue: 'Glue',
  awsana_kinesis: 'Kinesis',
  awsana_opensearch: 'OpenSearchService',
  awsana_lake_formation: 'LakeFormation',
  awsana_firehose: 'DataFirehose',
  awsana_redshift_ml: 'RedshiftML',
  awsana_msk: 'ManagedStreamingforApacheKafka',
  awsana_flink: 'ManagedServiceforApacheFlink',
  awsana_glue_databrew: 'GlueDataBrew',
  awsana_entity_resolution: 'EntityResolution',
  awsana_finspace: 'FinSpace',
  awsana_datazone: 'DataZone',
  awsana_clean_rooms: 'CleanRooms',
  awsana_cloudsearch: 'CloudSearch',
};

const AWS_INTEGRATION_MAP = {
  awsint_eventbridge: 'EventBridge',
  awsint_step_functions: 'StepFunctions',
  awsint_sns: 'SimpleNotificationService',
  awsint_sqs: 'SimpleQueueService',
  awsint_appsync: 'AppSync',
  awsint_mwaa: 'ManagedWorkflowsforApacheAirflow',
  awsint_express_workflows: 'ExpressWorkflows',
};

/** Architecture PNGs — additional categories under public/icons/aws-plantuml/ */
const AWS_COMPUTE_MAP = {
  awscmp_apprunner: 'AppRunner',
  awscmp_batch: 'Batch',
  awscmp_ec2: 'EC2',
  awscmp_ec2_autoscaling: 'EC2AutoScaling',
  awscmp_ec2_spot: 'EC2SpotInstance',
  awscmp_elastic_beanstalk: 'ElasticBeanstalk',
  awscmp_lambda: 'Lambda',
  awscmp_lambda_function: 'LambdaLambdaFunction',
  awscmp_lightsail: 'Lightsail',
  awscmp_outposts: 'Outpostsfamily',
  awscmp_wavelength: 'Wavelength',
  awscmp_local_zones: 'LocalZones',
  awscmp_serverless_repo: 'ServerlessApplicationRepository',
  awscmp_parallel_cluster: 'ParallelCluster',
  awscmp_nitro_enclaves: 'NitroEnclaves',
  awscmp_simspace_weaver: 'SimSpaceWeaver',
};

const AWS_CONTAINERS_MAP = {
  awsctr_ecr: 'ElasticContainerRegistry',
  awsctr_ecs: 'ElasticContainerService',
  awsctr_eks: 'ElasticKubernetesService',
  awsctr_fargate_icon: 'Fargate',
  awsctr_eks_anywhere: 'EKSAnywhere',
  awsctr_ecs_anywhere: 'ECSAnywhere',
  awsctr_rosa: 'RedHatOpenShiftServiceonAWS',
};

const AWS_DATABASE_PLANT_MAP = {
  awsdbp_aurora: 'Aurora',
  awsdbp_rds: 'RDS',
  awsdbp_dynamodb: 'DynamoDB',
  awsdbp_elasticache: 'ElastiCache',
  awsdbp_documentdb: 'DocumentDB',
  awsdbp_neptune: 'Neptune',
  awsdbp_memorydb: 'MemoryDB',
  awsdbp_keyspaces: 'Keyspaces',
  awsdbp_dms: 'DatabaseMigrationService',
  awsdbp_timestream: 'Timestream',
};

const AWS_STORAGE_PLANT_MAP = {
  awsstor_s3: 'SimpleStorageService',
  awsstor_ebs: 'ElasticBlockStore',
  awsstor_efs: 'EFS',
  awsstor_fsx: 'FSx',
  awsstor_backup: 'Backup',
  awsstor_snowball: 'Snowball',
  awsstor_snowball_edge: 'SnowballEdge',
  awsstor_storage_gateway: 'StorageGateway',
};

const AWS_NETWORKING_MAP = {
  awsnet_cloudfront: 'CloudFront',
  awsnet_apigateway: 'APIGateway',
  awsnet_route53: 'Route53',
  awsnet_transit_gateway: 'TransitGateway',
  awsnet_direct_connect: 'DirectConnect',
  awsnet_global_accelerator: 'GlobalAccelerator',
  awsnet_private_link: 'PrivateLink',
  awsnet_app_mesh: 'AppMesh',
  awsnet_cloud_map: 'CloudMap',
  awsnet_client_vpn: 'ClientVPN',
  awsnet_site_to_site_vpn: 'SitetoSiteVPN',
  awsnet_alb: 'ElasticLoadBalancingApplicationLoadBalancer',
  awsnet_nlb: 'ElasticLoadBalancingNetworkLoadBalancer',
  awsnet_gwlb: 'ElasticLoadBalancingGatewayLoadBalancer',
};

const AWS_SECURITY_MAP = {
  awssec_iam: 'IdentityandAccessManagement',
  awssec_kms: 'KeyManagementService',
  awssec_waf: 'WAF',
  awssec_shield: 'Shield',
  awssec_guardduty: 'GuardDuty',
  awssec_security_hub: 'SecurityHub',
  awssec_macie: 'Macie',
  awssec_inspector: 'Inspector',
  awssec_acm: 'CertificateManager',
  awssec_secrets: 'SecretsManager',
  awssec_network_firewall: 'NetworkFirewall',
  awssec_firewall_manager: 'FirewallManager',
  awssec_iam_identity_center: 'IAMIdentityCenter',
  awssec_detective: 'Detective',
  awssec_security_lake: 'SecurityLake',
};

const AWS_MANAGEMENT_MAP = {
  awsgov_cloudformation: 'CloudFormation',
  awsgov_cloudtrail: 'CloudTrail',
  awsgov_cloudwatch: 'CloudWatch',
  awsgov_systems_manager: 'SystemsManager',
  awsgov_config: 'Config',
  awsgov_control_tower: 'ControlTower',
  awsgov_organizations: 'Organizations',
  awsgov_autoscaling: 'AutoScaling',
  awsgov_resource_explorer: 'ResourceExplorer',
  awsgov_service_catalog: 'ServiceCatalog',
  awsgov_health: 'HealthDashboard',
  awsgov_compute_optimizer: 'ComputeOptimizer',
};

const AWS_DEVELOPER_MAP = {
  awsdev_codebuild: 'CodeBuild',
  awsdev_codedeploy: 'CodeDeploy',
  awsdev_codepipeline: 'CodePipeline',
  awsdev_codecommit: 'CodeCommit',
  awsdev_codeartifact: 'CodeArtifact',
  awsdev_cloud9: 'Cloud9',
  awsdev_cloudshell: 'CloudShell',
  awsdev_xray: 'XRay',
  awsdev_cdk: 'CloudDevelopmentKit',
};

const AWS_MIGRATION_MAP = {
  awsmigr_datasync: 'DataSync',
  awsmigr_transfer_family: 'TransferFamily',
  awsmigr_mgn: 'ApplicationMigrationService',
  awsmigr_mainframe: 'MainframeModernization',
};

const AWS_QUANTUM_MAP = {
  aws_quantum_braket: 'Braket',
};

/** @typedef {{ kind: 'path', title: string, hex: string, path: string } | { kind: 'url', title: string, hex: string, url: string }} IconSpec */

/** @type {Record<string, IconSpec>} */
export const ICON_BY_KEY = {
  kubernetes: fromSimple(siKubernetes),
  k8s_pod: k8sResource('pod', 'Pod'),
  k8s_deploy: k8sResource('deploy', 'Deployment'),
  k8s_rs: k8sResource('rs', 'ReplicaSet'),
  k8s_sts: k8sResource('sts', 'StatefulSet'),
  k8s_ds: k8sResource('ds', 'DaemonSet'),
  k8s_job: k8sResource('job', 'Job'),
  k8s_cronjob: k8sResource('cronjob', 'CronJob'),
  k8s_svc: k8sResource('svc', 'Service'),
  k8s_ingress: k8sResource('ing', 'Ingress'),
  k8s_ep: k8sResource('ep', 'Endpoints'),
  k8s_pvc: k8sResource('pvc', 'PersistentVolumeClaim'),
  k8s_pv: k8sResource('pv', 'PersistentVolume'),
  k8s_sc: k8sResource('sc', 'StorageClass'),
  k8s_vol: k8sResource('vol', 'Volume'),
  k8s_cm: k8sResource('cm', 'ConfigMap'),
  k8s_secret: k8sResource('secret', 'Secret'),
  k8s_ns: k8sResource('ns', 'Namespace'),
  k8s_hpa: k8sResource('hpa', 'HorizontalPodAutoscaler'),
  k8s_netpol: k8sResource('netpol', 'NetworkPolicy'),
  k8s_role: k8sResource('role', 'Role'),
  k8s_crole: k8sResource('c-role', 'ClusterRole'),
  k8s_rb: k8sResource('rb', 'RoleBinding'),
  k8s_crb: k8sResource('crb', 'ClusterRoleBinding'),
  k8s_sa: k8sResource('sa', 'ServiceAccount'),
  k8s_quota: k8sResource('quota', 'ResourceQuota'),
  k8s_limits: k8sResource('limits', 'LimitRange'),
  k8s_crd: k8sResource('crd', 'CustomResourceDefinition'),
  docker: fromSimple(siDocker),
  helm: fromSimple(siHelm),
  argo: fromSimple(siArgo),
  terraform: fromSimple(siTerraform),
  amazoniam: fromSimple(siAmazoniam),
  amazoncognito: fromSimple(siAmazoncognito),
  amazondocumentdb: fromSimple(siAmazondocumentdb),
  amazonelasticache: fromSimple(siAmazonelasticache),
  amazonredshift: fromSimple(siAmazonredshift),
  amazonroute53: fromSimple(siAmazonroute53),
  amazon_ses: fromSimple(siAmazonsimpleemailservice),
  awsamplify: fromSimple(siAwsamplify),
  awselb: fromSimple(siAwselasticloadbalancing),
  awsfargate: fromSimple(siAwsfargate),
  awsorganizations: fromSimple(siAwsorganizations),
  awssecretsmanager: fromSimple(siAwssecretsmanager),
  tensorflow: fromSimple(siTensorflow),
  pytorch: fromSimple(siPytorch),
  huggingface: fromSimple(siHuggingface),
  jupyter: fromSimple(siJupyter),
  keras: fromSimple(siKeras),
  scikitlearn: fromSimple(siScikitlearn),
  mlflow: fromSimple(siMlflow),
  langchain: fromSimple(siLangchain),
  openai: fromSimple(siOpenai),
  anthropic: fromSimple(siAnthropic),
  ollama: fromSimple(siOllama),
  databricks: fromSimple(siDatabricks),
  apachespark: fromSimple(siApachespark),
  snowflake: fromSimple(siSnowflake),
  neo4j: fromSimple(siNeo4j),
  amazoneks: fromSimple(siAmazoneks),
  amazonec2: fromSimple(siAmazonec2),
  amazons3: fromSimple(siAmazons3),
  amazonrds: fromSimple(siAmazonrds),
  awslambda: fromSimple(siAwslambda),
  amazondynamodb: fromSimple(siAmazondynamodb),
  amazonapigateway: fromSimple(siAmazonapigateway),
  amazonsqs: fromSimple(siAmazonsqs),
  amazoncloudwatch: fromSimple(siAmazoncloudwatch),
  amazonwebservices: fromSimple(siAmazonwebservices),
  amazonecs: fromSimple(siAmazonecs),
  googlecloud: fromSimple(siGooglecloud),
  azure: {
    kind: 'url',
    title: 'Microsoft Azure',
    hex: '0078D4',
    url: '/icons/azure.svg',
  },
  cloudflare: fromSimple(siCloudflare),
  fastly: fromSimple(siFastly),
  akamai: fromSimple(siAkamai),
  keycdn: fromSimple(siKeycdn),
  nextdns: fromSimple(siNextdns),
  wireguard: fromSimple(siWireguard),
  tailscale: fromSimple(siTailscale),
  zerotier: fromSimple(siZerotier),
  openvpn: fromSimple(siOpenvpn),
  f5: fromSimple(siF5),
  fortinet: fromSimple(siFortinet),
  juniper: fromSimple(siJunipernetworks),
  paloaltonetworks: fromSimple(siPaloaltonetworks),
  digitalocean: fromSimple(siDigitalocean),
  hetzner: fromSimple(siHetzner),
  scaleway: fromSimple(siScaleway),
  vercel: fromSimple(siVercel),
  postgresql: fromSimple(siPostgresql),
  redis: fromSimple(siRedis),
  mongodb: fromSimple(siMongodb),
  nginx: fromSimple(siNginx),
  rabbitmq: fromSimple(siRabbitmq),
  kafka: fromSimple(siApachekafka),
  grafana: fromSimple(siGrafana),
  prometheus: fromSimple(siPrometheus),
  github: fromSimple(siGithub),
  github_actions: fromSimple(siGithubactions),
  github_copilot: fromSimple(siGithubcopilot),
  gitlab: fromSimple(siGitlab),
  bitbucket: fromSimple(siBitbucket),
  gitea: fromSimple(siGitea),
  forgejo: fromSimple(siForgejo),
  gitkraken: fromSimple(siGitkraken),
  git_lfs: fromSimple(siGitlfs),
  gitpod: fromSimple(siGitpod),
  jenkins: fromSimple(siJenkins),
  circleci: fromSimple(siCircleci),
  travisci: fromSimple(siTravisci),
  teamcity: fromSimple(siTeamcity),
  bamboo_ci: fromSimple(siBamboo),
  buildkite: fromSimple(siBuildkite),
  drone_ci: fromSimple(siDrone),
  concourse: fromSimple(siConcourse),
  codefresh: fromSimple(siCodefresh),
  octopus_deploy: fromSimple(siOctopusdeploy),
  buddy_ci: fromSimple(siBuddy),
  semaphore_ci: fromSimple(siSemaphoreci),
  tekton: fromSimple(siTekton),
  spinnaker: fromSimple(siSpinnaker),
  flux_cd: fromSimple(siFlux),
  jfrog: fromSimple(siJfrog),
  jfrog_pipelines: fromSimple(siJfrogpipelines),
  dependabot: fromSimple(siDependabot),
  renovate: fromSimple(siRenovate),
  pre_commit: fromSimple(siPrecommit),
  bitrise: fromSimple(siBitrise),
  fastlane: fromSimple(siFastlane),
  xcode: fromSimple(siXcode),
  maven: fromSimple(siApachemaven),
  gradle: fromSimple(siGradle),
  npm: fromSimple(siNpm),
  yarn: fromSimple(siYarn),
  pnpm: fromSimple(siPnpm),
  jetbrains: fromSimple(siJetbrains),
  opentofu: fromSimple(siOpentofu),
  pulumi: fromSimple(siPulumi),
  ansible: fromSimple(siAnsible),
  puppet: fromSimple(siPuppet),
  chef: fromSimple(siChef),
  saltstack: fromSimple(siSaltproject),
  packer: fromSimple(siPacker),
  vault: fromSimple(siVault),
  consul: fromSimple(siConsul),
  nomad: fromSimple(siNomad),
  vagrant: fromSimple(siVagrant),
  serverless_framework: fromSimple(siServerless),
  datadog: fromSimple(siDatadog),
  newrelic: fromSimple(siNewrelic),
  splunk: fromSimple(siSplunk),
  elastic: fromSimple(siElastic),
  elasticsearch: fromSimple(siElasticsearch),
  kibana: fromSimple(siKibana),
  sentry: fromSimple(siSentry),
  dynatrace: fromSimple(siDynatrace),
  pagerduty: fromSimple(siPagerduty),
  opsgenie: fromSimple(siOpsgenie),
  jaeger: fromSimple(siJaeger),
  opentelemetry: fromSimple(siOpentelemetry),
  thanos: fromSimple(siThanos),
  fluentbit: fromSimple(siFluentbit),
  fluentd: fromSimple(siFluentd),
  graylog: fromSimple(siGraylog),
  icinga: fromSimple(siIcinga),
  checkmk: fromSimple(siCheckmk),
  pingdom: fromSimple(siPingdom),
  statuspage: fromSimple(siStatuspage),
  uptime_kuma: fromSimple(siUptimekuma),
  snyk: fromSimple(siSnyk),
  trivy: fromSimple(siTrivy),
  falco: fromSimple(siFalco),
  codecov: fromSimple(siCodecov),
  sonarqube: fromSimple(siSonarqube),
  sonatype: fromSimple(siSonatype),
  jest: fromSimple(siJest),
  mocha: fromSimple(siMocha),
  vitest: fromSimple(siVitest),
  cypress: fromSimple(siCypress),
  selenium: fromSimple(siSelenium),
  eslint: fromSimple(siEslint),
  prettier: fromSimple(siPrettier),
  swagger: fromSimple(siSwagger),
  openapi_initiative: fromSimple(siOpenapiinitiative),
  postman: fromSimple(siPostman),
  insomnia: fromSimple(siInsomnia),
  envoy: fromSimple(siEnvoyproxy),
  istio: fromSimple(siIstio),
  linkerd: fromSimple(siLinkerd),
  cilium: fromSimple(siCilium),
  traefik: fromSimple(siTraefikproxy),
  caddy: fromSimple(siCaddy),
  portainer: fromSimple(siPortainer),
  rancher: fromSimple(siRancher),
  podman: fromSimple(siPodman),
  containerd: fromSimple(siContainerd),
  harbor: fromSimple(siHarbor),
  artifacthub: fromSimple(siArtifacthub),
  service: {
    kind: 'path',
    title: 'Service',
    hex: '64748b',
    path: 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z',
  },
  api: {
    kind: 'path',
    title: 'API',
    hex: '6366f1',
    path: 'M8 5v14l11-7z',
  },
  queue: {
    kind: 'path',
    title: 'Queue',
    hex: 'd97706',
    path: 'M4 6h16v2H4zm0 5h16v2H4zm0 5h16v2H4z',
  },
  diagram_text: {
    kind: 'path',
    title: 'Text note',
    hex: '475569',
    path: 'M5 5h14v2H5V5zm0 4h14v2H5V9zm0 4h11v2H5v-2zm0 4h14v2H5v-2z',
  },
  ...SYS_TRAFFIC_FLOW_ICONS,
  ...mapAwsArch('ArtificialIntelligence', AWS_AI_MAP),
  ...mapAwsArch('Analytics', AWS_ANALYTICS_MAP),
  ...mapAwsArch('ApplicationIntegration', AWS_INTEGRATION_MAP),
  ...mapAwsArch('Compute', AWS_COMPUTE_MAP),
  ...mapAwsArch('Containers', AWS_CONTAINERS_MAP),
  ...mapAwsArch('Database', AWS_DATABASE_PLANT_MAP),
  ...mapAwsArch('Storage', AWS_STORAGE_PLANT_MAP),
  ...mapAwsArch('NetworkingContentDelivery', AWS_NETWORKING_MAP),
  ...mapAwsArch('SecurityIdentityCompliance', AWS_SECURITY_MAP),
  ...mapAwsArch('ManagementGovernance', AWS_MANAGEMENT_MAP),
  ...mapAwsArch('DeveloperTools', AWS_DEVELOPER_MAP),
  ...mapAwsArch('MigrationModernization', AWS_MIGRATION_MAP),
  ...mapAwsArch('QuantumTechnologies', AWS_QUANTUM_MAP),
};

export const DEFAULT_ICON_KEY = 'service';

export function resolveIcon(iconKey) {
  return ICON_BY_KEY[iconKey] || ICON_BY_KEY[DEFAULT_ICON_KEY];
}

export const PALETTE_GROUPS = [
  {
    title: 'System & traffic flow',
    items: [
      { iconKey: 'sys_browser', defaultLabel: 'Web / browser', search: 'http client internet traffic user agent' },
      { iconKey: 'sys_desktop', defaultLabel: 'Desktop', search: 'pc workstation client' },
      { iconKey: 'sys_laptop', defaultLabel: 'Laptop', search: 'notebook client' },
      { iconKey: 'sys_mobile', defaultLabel: 'Mobile', search: 'phone tablet client' },
      { iconKey: 'sys_user', defaultLabel: 'User', search: 'person end client actor' },
      { iconKey: 'sys_devices', defaultLabel: 'Devices', search: 'clients fleet endpoints' },
      { iconKey: 'sys_cloud', defaultLabel: 'Cloud (generic)', search: 'saas hosted' },
      { iconKey: 'sys_server', defaultLabel: 'Server', search: 'host vm compute' },
      { iconKey: 'sys_router', defaultLabel: 'Router', search: 'gateway edge cpe' },
      { iconKey: 'sys_switch', defaultLabel: 'Switch', search: 'l2 network fabric' },
      { iconKey: 'sys_firewall', defaultLabel: 'Firewall', search: 'security perimeter' },
      { iconKey: 'sys_load_balancer', defaultLabel: 'Load balancer', search: 'lb traffic split ha proxy' },
      { iconKey: 'sys_network', defaultLabel: 'Network', search: 'vpc topology connection' },
      { iconKey: 'sys_lan', defaultLabel: 'LAN segment', search: 'subnet vlan link' },
      { iconKey: 'sys_ethernet', defaultLabel: 'Ethernet / NIC', search: 'cable nic physical' },
      { iconKey: 'sys_wifi', defaultLabel: 'Wireless', search: 'wifi access point ap' },
      { iconKey: 'sys_dns', defaultLabel: 'DNS', search: 'name resolution lookup' },
      { iconKey: 'sys_ip', defaultLabel: 'IP / subnet', search: 'address routing' },
      { iconKey: 'sys_certificate', defaultLabel: 'TLS certificate', search: 'https ssl x509' },
      { iconKey: 'sys_lock', defaultLabel: 'Encryption', search: 'tls secure channel' },
      { iconKey: 'sys_filter', defaultLabel: 'Filter / rules', search: 'waf acl policy' },
      { iconKey: 'sys_disk', defaultLabel: 'Disk', search: 'storage volume block hdd ssd' },
      { iconKey: 'sys_nas', defaultLabel: 'NAS', search: 'file storage array san' },
      { iconKey: 'sys_folder_share', defaultLabel: 'Shared folder', search: 'smb nfs file share' },
      { iconKey: 'sys_database', defaultLabel: 'Database', search: 'persistence sql nosql' },
      { iconKey: 'sys_memory', defaultLabel: 'RAM', search: 'memory dram cache' },
      { iconKey: 'sys_cpu', defaultLabel: 'CPU', search: 'processor compute core' },
      { iconKey: 'sys_usb', defaultLabel: 'USB drive', search: 'removable media' },
      { iconKey: 'sys_sync', defaultLabel: 'Sync / replication', search: 'mirror copy dr' },
      { iconKey: 'sys_traffic_branch', defaultLabel: 'Traffic branch', search: 'split fork path' },
      { iconKey: 'sys_routing', defaultLabel: 'Routing / policy', search: 'decision route rules' },
      { iconKey: 'sys_latency', defaultLabel: 'Latency', search: 'delay wait timing' },
      { iconKey: 'sys_metrics', defaultLabel: 'Metrics', search: 'layers tiers waterfall' },
      { iconKey: 'sys_bandwidth', defaultLabel: 'Throughput', search: 'bandwidth performance speed' },
      { iconKey: 'api', defaultLabel: 'API call', search: 'rest grpc request response traffic' },
      { iconKey: 'queue', defaultLabel: 'Queue', search: 'async message buffer traffic' },
    ],
  },
  {
    title: 'Kubernetes resources',
    items: [
      { iconKey: 'k8s_pod', defaultLabel: 'Pod' },
      { iconKey: 'k8s_deploy', defaultLabel: 'Deployment' },
      { iconKey: 'k8s_rs', defaultLabel: 'ReplicaSet' },
      { iconKey: 'k8s_sts', defaultLabel: 'StatefulSet' },
      { iconKey: 'k8s_ds', defaultLabel: 'DaemonSet' },
      { iconKey: 'k8s_job', defaultLabel: 'Job' },
      { iconKey: 'k8s_cronjob', defaultLabel: 'CronJob' },
      { iconKey: 'k8s_svc', defaultLabel: 'Service' },
      { iconKey: 'k8s_ingress', defaultLabel: 'Ingress' },
      { iconKey: 'k8s_ep', defaultLabel: 'Endpoints' },
      { iconKey: 'k8s_pvc', defaultLabel: 'PersistentVolumeClaim' },
      { iconKey: 'k8s_pv', defaultLabel: 'PersistentVolume' },
      { iconKey: 'k8s_sc', defaultLabel: 'StorageClass' },
      { iconKey: 'k8s_vol', defaultLabel: 'Volume' },
      { iconKey: 'k8s_cm', defaultLabel: 'ConfigMap' },
      { iconKey: 'k8s_secret', defaultLabel: 'Secret' },
      { iconKey: 'k8s_ns', defaultLabel: 'Namespace' },
      { iconKey: 'k8s_hpa', defaultLabel: 'HorizontalPodAutoscaler' },
      { iconKey: 'k8s_netpol', defaultLabel: 'NetworkPolicy' },
      { iconKey: 'k8s_role', defaultLabel: 'Role' },
      { iconKey: 'k8s_crole', defaultLabel: 'ClusterRole' },
      { iconKey: 'k8s_rb', defaultLabel: 'RoleBinding' },
      { iconKey: 'k8s_crb', defaultLabel: 'ClusterRoleBinding' },
      { iconKey: 'k8s_sa', defaultLabel: 'ServiceAccount' },
      { iconKey: 'k8s_quota', defaultLabel: 'ResourceQuota' },
      { iconKey: 'k8s_limits', defaultLabel: 'LimitRange' },
      { iconKey: 'k8s_crd', defaultLabel: 'CustomResourceDefinition' },
    ],
  },
  {
    title: 'Kubernetes & delivery',
    items: [
      { iconKey: 'kubernetes', defaultLabel: 'Kubernetes cluster' },
      { iconKey: 'docker', defaultLabel: 'Container' },
      { iconKey: 'helm', defaultLabel: 'Helm release' },
      { iconKey: 'argo', defaultLabel: 'Argo CD' },
      { iconKey: 'terraform', defaultLabel: 'Terraform' },
    ],
  },
  {
    title: 'AWS',
    items: [
      { iconKey: 'amazonwebservices', defaultLabel: 'AWS account' },
      { iconKey: 'amazoniam', defaultLabel: 'IAM' },
      { iconKey: 'awsorganizations', defaultLabel: 'Organizations' },
      { iconKey: 'amazoneks', defaultLabel: 'EKS' },
      { iconKey: 'amazonecs', defaultLabel: 'ECS' },
      { iconKey: 'awsfargate', defaultLabel: 'Fargate' },
      { iconKey: 'amazonec2', defaultLabel: 'EC2' },
      { iconKey: 'awselb', defaultLabel: 'Elastic Load Balancing' },
      { iconKey: 'amazons3', defaultLabel: 'S3' },
      { iconKey: 'amazonrds', defaultLabel: 'RDS' },
      { iconKey: 'amazonredshift', defaultLabel: 'Redshift' },
      { iconKey: 'amazondynamodb', defaultLabel: 'DynamoDB' },
      { iconKey: 'amazondocumentdb', defaultLabel: 'DocumentDB' },
      { iconKey: 'amazonelasticache', defaultLabel: 'ElastiCache' },
      { iconKey: 'awslambda', defaultLabel: 'Lambda' },
      { iconKey: 'amazonapigateway', defaultLabel: 'API Gateway' },
      { iconKey: 'amazonsqs', defaultLabel: 'SQS' },
      { iconKey: 'amazonroute53', defaultLabel: 'Route 53' },
      { iconKey: 'amazoncloudwatch', defaultLabel: 'CloudWatch' },
      { iconKey: 'awssecretsmanager', defaultLabel: 'Secrets Manager' },
      { iconKey: 'amazoncognito', defaultLabel: 'Cognito' },
      { iconKey: 'amazon_ses', defaultLabel: 'SES' },
      { iconKey: 'awsamplify', defaultLabel: 'Amplify' },
    ],
  },
  {
    title: 'AWS AI & machine learning',
    items: [
      { iconKey: 'awsai_bedrock', defaultLabel: 'Amazon Bedrock' },
      { iconKey: 'awsai_bedrock_agent_core', defaultLabel: 'Bedrock Agent Core' },
      { iconKey: 'awsai_sagemaker', defaultLabel: 'Amazon SageMaker' },
      { iconKey: 'awsai_sagemaker_ground_truth', defaultLabel: 'SageMaker Ground Truth' },
      { iconKey: 'awsai_sagemaker_notebook', defaultLabel: 'SageMaker Notebook' },
      { iconKey: 'awsai_comprehend', defaultLabel: 'Amazon Comprehend' },
      { iconKey: 'awsai_comprehend_medical', defaultLabel: 'Comprehend Medical' },
      { iconKey: 'awsai_rekognition', defaultLabel: 'Amazon Rekognition' },
      { iconKey: 'awsai_textract', defaultLabel: 'Amazon Textract' },
      { iconKey: 'awsai_lex', defaultLabel: 'Amazon Lex' },
      { iconKey: 'awsai_polly', defaultLabel: 'Amazon Polly' },
      { iconKey: 'awsai_transcribe', defaultLabel: 'Amazon Transcribe' },
      { iconKey: 'awsai_translate', defaultLabel: 'Amazon Translate' },
      { iconKey: 'awsai_kendra', defaultLabel: 'Amazon Kendra' },
      { iconKey: 'awsai_personalize', defaultLabel: 'Amazon Personalize' },
      { iconKey: 'awsai_forecast', defaultLabel: 'Amazon Forecast' },
      { iconKey: 'awsai_fraud_detector', defaultLabel: 'Amazon Fraud Detector' },
      { iconKey: 'awsai_deep_racer', defaultLabel: 'AWS DeepRacer' },
      { iconKey: 'awsai_augmented_ai', defaultLabel: 'Amazon Augmented AI' },
      { iconKey: 'awsai_panorama', defaultLabel: 'AWS Panorama' },
      { iconKey: 'awsai_codeguru', defaultLabel: 'Amazon CodeGuru' },
      { iconKey: 'awsai_q', defaultLabel: 'Amazon Q' },
      { iconKey: 'awsai_nova', defaultLabel: 'Amazon Nova' },
      { iconKey: 'awsai_elastic_inference', defaultLabel: 'Elastic Inference' },
      { iconKey: 'awsai_pytorch_on_aws', defaultLabel: 'PyTorch on AWS' },
      { iconKey: 'awsai_tensorflow_on_aws', defaultLabel: 'TensorFlow on AWS' },
      { iconKey: 'awsai_deep_learning_containers', defaultLabel: 'Deep Learning Containers' },
      { iconKey: 'awsai_deep_learning_amis', defaultLabel: 'Deep Learning AMIs' },
      { iconKey: 'awsai_devops_guru', defaultLabel: 'DevOps Guru' },
      { iconKey: 'awsai_monitron', defaultLabel: 'Amazon Monitron' },
      { iconKey: 'awsai_lookout_equipment', defaultLabel: 'Lookout for Equipment' },
      { iconKey: 'awsai_lookout_vision', defaultLabel: 'Lookout for Vision' },
      { iconKey: 'awsai_codewhisperer', defaultLabel: 'CodeWhisperer' },
      { iconKey: 'awsai_health_scribe', defaultLabel: 'AWS HealthScribe' },
      { iconKey: 'awsai_neuron', defaultLabel: 'AWS Neuron' },
    ],
  },
  {
    title: 'AWS analytics & streaming',
    items: [
      { iconKey: 'awsana_athena', defaultLabel: 'Amazon Athena' },
      { iconKey: 'awsana_emr', defaultLabel: 'Amazon EMR' },
      { iconKey: 'awsana_glue', defaultLabel: 'AWS Glue' },
      { iconKey: 'awsana_glue_databrew', defaultLabel: 'Glue DataBrew' },
      { iconKey: 'awsana_kinesis', defaultLabel: 'Amazon Kinesis' },
      { iconKey: 'awsana_firehose', defaultLabel: 'Kinesis Data Firehose' },
      { iconKey: 'awsana_opensearch', defaultLabel: 'Amazon OpenSearch' },
      { iconKey: 'awsana_lake_formation', defaultLabel: 'Lake Formation' },
      { iconKey: 'awsana_redshift_ml', defaultLabel: 'Redshift ML' },
      { iconKey: 'awsana_msk', defaultLabel: 'Amazon MSK' },
      { iconKey: 'awsana_flink', defaultLabel: 'Managed Apache Flink' },
      { iconKey: 'awsana_entity_resolution', defaultLabel: 'Entity Resolution' },
      { iconKey: 'awsana_finspace', defaultLabel: 'Amazon FinSpace' },
      { iconKey: 'awsana_datazone', defaultLabel: 'Amazon DataZone' },
      { iconKey: 'awsana_clean_rooms', defaultLabel: 'AWS Clean Rooms' },
      { iconKey: 'awsana_cloudsearch', defaultLabel: 'Amazon CloudSearch' },
    ],
  },
  {
    title: 'AWS integration & workflows',
    items: [
      { iconKey: 'awsint_eventbridge', defaultLabel: 'EventBridge' },
      { iconKey: 'awsint_step_functions', defaultLabel: 'Step Functions' },
      { iconKey: 'awsint_express_workflows', defaultLabel: 'Express Workflows' },
      { iconKey: 'awsint_sns', defaultLabel: 'Amazon SNS' },
      { iconKey: 'awsint_sqs', defaultLabel: 'Amazon SQS' },
      { iconKey: 'awsint_appsync', defaultLabel: 'AWS AppSync' },
      { iconKey: 'awsint_mwaa', defaultLabel: 'Amazon MWAA' },
    ],
  },
  {
    title: 'AWS compute & serverless',
    items: [
      { iconKey: 'awscmp_apprunner', defaultLabel: 'App Runner' },
      { iconKey: 'awscmp_batch', defaultLabel: 'AWS Batch' },
      { iconKey: 'awscmp_ec2', defaultLabel: 'EC2' },
      { iconKey: 'awscmp_ec2_autoscaling', defaultLabel: 'EC2 Auto Scaling' },
      { iconKey: 'awscmp_ec2_spot', defaultLabel: 'EC2 Spot' },
      { iconKey: 'awscmp_elastic_beanstalk', defaultLabel: 'Elastic Beanstalk' },
      { iconKey: 'awscmp_lambda', defaultLabel: 'Lambda' },
      { iconKey: 'awscmp_lambda_function', defaultLabel: 'Lambda function' },
      { iconKey: 'awscmp_lightsail', defaultLabel: 'Lightsail' },
      { iconKey: 'awscmp_outposts', defaultLabel: 'Outposts' },
      { iconKey: 'awscmp_wavelength', defaultLabel: 'Wavelength' },
      { iconKey: 'awscmp_local_zones', defaultLabel: 'Local Zones' },
      { iconKey: 'awscmp_serverless_repo', defaultLabel: 'Serverless App Repository' },
      { iconKey: 'awscmp_parallel_cluster', defaultLabel: 'ParallelCluster' },
      { iconKey: 'awscmp_nitro_enclaves', defaultLabel: 'Nitro Enclaves' },
      { iconKey: 'awscmp_simspace_weaver', defaultLabel: 'SimSpace Weaver' },
    ],
  },
  {
    title: 'AWS containers & Kubernetes',
    items: [
      { iconKey: 'awsctr_ecr', defaultLabel: 'ECR' },
      { iconKey: 'awsctr_ecs', defaultLabel: 'ECS' },
      { iconKey: 'awsctr_eks', defaultLabel: 'EKS' },
      { iconKey: 'awsctr_fargate_icon', defaultLabel: 'Fargate' },
      { iconKey: 'awsctr_eks_anywhere', defaultLabel: 'EKS Anywhere' },
      { iconKey: 'awsctr_ecs_anywhere', defaultLabel: 'ECS Anywhere' },
      { iconKey: 'awsctr_rosa', defaultLabel: 'ROSA' },
    ],
  },
  {
    title: 'AWS databases',
    items: [
      { iconKey: 'awsdbp_aurora', defaultLabel: 'Aurora' },
      { iconKey: 'awsdbp_rds', defaultLabel: 'RDS' },
      { iconKey: 'awsdbp_dynamodb', defaultLabel: 'DynamoDB' },
      { iconKey: 'awsdbp_elasticache', defaultLabel: 'ElastiCache' },
      { iconKey: 'awsdbp_documentdb', defaultLabel: 'DocumentDB' },
      { iconKey: 'awsdbp_neptune', defaultLabel: 'Neptune' },
      { iconKey: 'awsdbp_memorydb', defaultLabel: 'MemoryDB' },
      { iconKey: 'awsdbp_keyspaces', defaultLabel: 'Keyspaces' },
      { iconKey: 'awsdbp_dms', defaultLabel: 'Database Migration Service' },
      { iconKey: 'awsdbp_timestream', defaultLabel: 'Timestream' },
    ],
  },
  {
    title: 'AWS storage & backup',
    items: [
      { iconKey: 'awsstor_s3', defaultLabel: 'S3' },
      { iconKey: 'awsstor_ebs', defaultLabel: 'EBS' },
      { iconKey: 'awsstor_efs', defaultLabel: 'EFS' },
      { iconKey: 'awsstor_fsx', defaultLabel: 'FSx' },
      { iconKey: 'awsstor_backup', defaultLabel: 'AWS Backup' },
      { iconKey: 'awsstor_snowball', defaultLabel: 'Snowball' },
      { iconKey: 'awsstor_snowball_edge', defaultLabel: 'Snowball Edge' },
      { iconKey: 'awsstor_storage_gateway', defaultLabel: 'Storage Gateway' },
    ],
  },
  {
    title: 'AWS networking & CDN',
    items: [
      { iconKey: 'awsnet_cloudfront', defaultLabel: 'CloudFront' },
      { iconKey: 'awsnet_apigateway', defaultLabel: 'API Gateway' },
      { iconKey: 'awsnet_route53', defaultLabel: 'Route 53' },
      { iconKey: 'awsnet_transit_gateway', defaultLabel: 'Transit Gateway' },
      { iconKey: 'awsnet_direct_connect', defaultLabel: 'Direct Connect' },
      { iconKey: 'awsnet_global_accelerator', defaultLabel: 'Global Accelerator' },
      { iconKey: 'awsnet_private_link', defaultLabel: 'PrivateLink' },
      { iconKey: 'awsnet_app_mesh', defaultLabel: 'App Mesh' },
      { iconKey: 'awsnet_cloud_map', defaultLabel: 'Cloud Map' },
      { iconKey: 'awsnet_client_vpn', defaultLabel: 'Client VPN' },
      { iconKey: 'awsnet_site_to_site_vpn', defaultLabel: 'Site-to-Site VPN' },
      { iconKey: 'awsnet_alb', defaultLabel: 'Application Load Balancer' },
      { iconKey: 'awsnet_nlb', defaultLabel: 'Network Load Balancer' },
      { iconKey: 'awsnet_gwlb', defaultLabel: 'Gateway Load Balancer' },
      { iconKey: 'awssec_network_firewall', defaultLabel: 'Network Firewall' },
    ],
  },
  {
    title: 'CDN, DNS, VPN & network edge',
    items: [
      { iconKey: 'cloudflare', defaultLabel: 'Cloudflare', search: 'cdn waf dns proxy' },
      { iconKey: 'fastly', defaultLabel: 'Fastly', search: 'cdn edge' },
      { iconKey: 'akamai', defaultLabel: 'Akamai', search: 'cdn edge' },
      { iconKey: 'keycdn', defaultLabel: 'KeyCDN', search: 'cdn' },
      { iconKey: 'nextdns', defaultLabel: 'NextDNS', search: 'dns resolver' },
      { iconKey: 'tailscale', defaultLabel: 'Tailscale', search: 'vpn mesh zero trust' },
      { iconKey: 'zerotier', defaultLabel: 'ZeroTier', search: 'vpn sdn overlay' },
      { iconKey: 'wireguard', defaultLabel: 'WireGuard', search: 'vpn tunnel' },
      { iconKey: 'openvpn', defaultLabel: 'OpenVPN', search: 'vpn' },
      { iconKey: 'f5', defaultLabel: 'F5 BIG-IP', search: 'load balancer adc waf' },
      { iconKey: 'fortinet', defaultLabel: 'Fortinet', search: 'firewall fortigate' },
      { iconKey: 'juniper', defaultLabel: 'Juniper Networks', search: 'router switch' },
      { iconKey: 'paloaltonetworks', defaultLabel: 'Palo Alto Networks', search: 'firewall ngfw' },
      { iconKey: 'envoy', defaultLabel: 'Envoy proxy', search: 'service mesh sidecar' },
      { iconKey: 'istio', defaultLabel: 'Istio', search: 'service mesh' },
      { iconKey: 'linkerd', defaultLabel: 'Linkerd', search: 'service mesh' },
      { iconKey: 'traefik', defaultLabel: 'Traefik', search: 'ingress reverse proxy' },
      { iconKey: 'cilium', defaultLabel: 'Cilium', search: 'cni ebpf network policy' },
      { iconKey: 'nginx', defaultLabel: 'NGINX', search: 'reverse proxy load balancer' },
    ],
  },
  {
    title: 'AWS security & compliance',
    items: [
      { iconKey: 'awssec_iam', defaultLabel: 'IAM' },
      { iconKey: 'awssec_kms', defaultLabel: 'KMS' },
      { iconKey: 'awssec_waf', defaultLabel: 'WAF' },
      { iconKey: 'awssec_shield', defaultLabel: 'Shield' },
      { iconKey: 'awssec_guardduty', defaultLabel: 'GuardDuty' },
      { iconKey: 'awssec_security_hub', defaultLabel: 'Security Hub' },
      { iconKey: 'awssec_macie', defaultLabel: 'Macie' },
      { iconKey: 'awssec_inspector', defaultLabel: 'Inspector' },
      { iconKey: 'awssec_acm', defaultLabel: 'Certificate Manager' },
      { iconKey: 'awssec_secrets', defaultLabel: 'Secrets Manager' },
      { iconKey: 'awssec_network_firewall', defaultLabel: 'Network Firewall' },
      { iconKey: 'awssec_firewall_manager', defaultLabel: 'Firewall Manager' },
      { iconKey: 'awssec_iam_identity_center', defaultLabel: 'IAM Identity Center' },
      { iconKey: 'awssec_detective', defaultLabel: 'Detective' },
      { iconKey: 'awssec_security_lake', defaultLabel: 'Security Lake' },
    ],
  },
  {
    title: 'AWS management & governance',
    items: [
      { iconKey: 'awsgov_cloudformation', defaultLabel: 'CloudFormation' },
      { iconKey: 'awsgov_cloudtrail', defaultLabel: 'CloudTrail' },
      { iconKey: 'awsgov_cloudwatch', defaultLabel: 'CloudWatch' },
      { iconKey: 'awsgov_systems_manager', defaultLabel: 'Systems Manager' },
      { iconKey: 'awsgov_config', defaultLabel: 'AWS Config' },
      { iconKey: 'awsgov_control_tower', defaultLabel: 'Control Tower' },
      { iconKey: 'awsgov_organizations', defaultLabel: 'Organizations' },
      { iconKey: 'awsgov_autoscaling', defaultLabel: 'Auto Scaling' },
      { iconKey: 'awsgov_resource_explorer', defaultLabel: 'Resource Explorer' },
      { iconKey: 'awsgov_service_catalog', defaultLabel: 'Service Catalog' },
      { iconKey: 'awsgov_health', defaultLabel: 'Health Dashboard' },
      { iconKey: 'awsgov_compute_optimizer', defaultLabel: 'Compute Optimizer' },
    ],
  },
  {
    title: 'AWS developer & CI/CD',
    items: [
      { iconKey: 'awsdev_codebuild', defaultLabel: 'CodeBuild' },
      { iconKey: 'awsdev_codedeploy', defaultLabel: 'CodeDeploy' },
      { iconKey: 'awsdev_codepipeline', defaultLabel: 'CodePipeline' },
      { iconKey: 'awsdev_codecommit', defaultLabel: 'CodeCommit' },
      { iconKey: 'awsdev_codeartifact', defaultLabel: 'CodeArtifact' },
      { iconKey: 'awsdev_cloud9', defaultLabel: 'Cloud9' },
      { iconKey: 'awsdev_cloudshell', defaultLabel: 'CloudShell' },
      { iconKey: 'awsdev_xray', defaultLabel: 'X-Ray' },
      { iconKey: 'awsdev_cdk', defaultLabel: 'CDK' },
    ],
  },
  {
    title: 'AWS migration & transfer',
    items: [
      { iconKey: 'awsmigr_datasync', defaultLabel: 'DataSync' },
      { iconKey: 'awsmigr_transfer_family', defaultLabel: 'Transfer Family' },
      { iconKey: 'awsmigr_mgn', defaultLabel: 'Application Migration (MGN)' },
      { iconKey: 'awsmigr_mainframe', defaultLabel: 'Mainframe Modernization' },
    ],
  },
  {
    title: 'AWS quantum',
    items: [{ iconKey: 'aws_quantum_braket', defaultLabel: 'Braket' }],
  },
  {
    title: 'ML & AI ecosystem',
    items: [
      { iconKey: 'tensorflow', defaultLabel: 'TensorFlow' },
      { iconKey: 'pytorch', defaultLabel: 'PyTorch' },
      { iconKey: 'huggingface', defaultLabel: 'Hugging Face' },
      { iconKey: 'jupyter', defaultLabel: 'Jupyter' },
      { iconKey: 'keras', defaultLabel: 'Keras' },
      { iconKey: 'scikitlearn', defaultLabel: 'scikit-learn' },
      { iconKey: 'mlflow', defaultLabel: 'MLflow' },
      { iconKey: 'langchain', defaultLabel: 'LangChain' },
      { iconKey: 'openai', defaultLabel: 'OpenAI' },
      { iconKey: 'anthropic', defaultLabel: 'Anthropic' },
      { iconKey: 'ollama', defaultLabel: 'Ollama' },
      { iconKey: 'databricks', defaultLabel: 'Databricks' },
      { iconKey: 'apachespark', defaultLabel: 'Apache Spark' },
      { iconKey: 'snowflake', defaultLabel: 'Snowflake' },
      { iconKey: 'neo4j', defaultLabel: 'Neo4j' },
    ],
  },
  {
    title: 'Microsoft Azure',
    items: [
      { iconKey: 'azure', defaultLabel: 'Azure subscription' },
      { iconKey: 'azure', defaultLabel: 'Azure AKS' },
      { iconKey: 'azure', defaultLabel: 'Azure Functions' },
      { iconKey: 'azure', defaultLabel: 'Azure App Service' },
      { iconKey: 'azure', defaultLabel: 'Azure API Management' },
      { iconKey: 'azure', defaultLabel: 'Azure SQL' },
      { iconKey: 'azure', defaultLabel: 'Azure Cosmos DB' },
      { iconKey: 'azure', defaultLabel: 'Azure Storage' },
      { iconKey: 'azure', defaultLabel: 'Azure Key Vault' },
      { iconKey: 'azure', defaultLabel: 'Azure Service Bus' },
      { iconKey: 'azure', defaultLabel: 'Azure Event Hubs' },
      { iconKey: 'azure', defaultLabel: 'Azure Monitor' },
      { iconKey: 'azure', defaultLabel: 'Azure Container Apps' },
    ],
  },
  {
    title: 'Cloud providers',
    items: [
      { iconKey: 'googlecloud', defaultLabel: 'Google Cloud' },
      { iconKey: 'cloudflare', defaultLabel: 'Cloudflare' },
      { iconKey: 'digitalocean', defaultLabel: 'DigitalOcean' },
      { iconKey: 'hetzner', defaultLabel: 'Hetzner' },
      { iconKey: 'scaleway', defaultLabel: 'Scaleway' },
      { iconKey: 'vercel', defaultLabel: 'Vercel' },
    ],
  },
  {
    title: 'Data & messaging',
    items: [
      { iconKey: 'postgresql', defaultLabel: 'PostgreSQL' },
      { iconKey: 'redis', defaultLabel: 'Redis' },
      { iconKey: 'mongodb', defaultLabel: 'MongoDB' },
      { iconKey: 'rabbitmq', defaultLabel: 'RabbitMQ' },
      { iconKey: 'kafka', defaultLabel: 'Kafka' },
      { iconKey: 'nginx', defaultLabel: 'NGINX' },
    ],
  },
  {
    title: 'Git & GitHub',
    items: [
      { iconKey: 'github', defaultLabel: 'GitHub', search: 'git repository source code' },
      { iconKey: 'github_actions', defaultLabel: 'GitHub Actions', search: 'gha workflow ci cd pipeline' },
      { iconKey: 'github_copilot', defaultLabel: 'GitHub Copilot', search: 'ai pair programming' },
      { iconKey: 'gitlab', defaultLabel: 'GitLab', search: 'git ci cd merge' },
      { iconKey: 'bitbucket', defaultLabel: 'Bitbucket', search: 'atlassian git' },
      { iconKey: 'gitea', defaultLabel: 'Gitea', search: 'git self hosted' },
      { iconKey: 'forgejo', defaultLabel: 'Forgejo', search: 'git gitea fork' },
      { iconKey: 'gitkraken', defaultLabel: 'GitKraken', search: 'git client gui' },
      { iconKey: 'git_lfs', defaultLabel: 'Git LFS', search: 'large file storage' },
      { iconKey: 'gitpod', defaultLabel: 'Gitpod', search: 'cloud dev environment' },
    ],
  },
  {
    title: 'CI/CD & build',
    items: [
      { iconKey: 'jenkins', defaultLabel: 'Jenkins', search: 'pipeline groovy' },
      { iconKey: 'circleci', defaultLabel: 'CircleCI', search: 'ci cd orbs' },
      { iconKey: 'travisci', defaultLabel: 'Travis CI', search: 'travis yaml' },
      { iconKey: 'teamcity', defaultLabel: 'TeamCity', search: 'jetbrains build' },
      { iconKey: 'bamboo_ci', defaultLabel: 'Bamboo', search: 'atlassian ci' },
      { iconKey: 'buildkite', defaultLabel: 'Buildkite', search: 'agents pipeline' },
      { iconKey: 'drone_ci', defaultLabel: 'Drone CI', search: 'container pipeline' },
      { iconKey: 'concourse', defaultLabel: 'Concourse', search: 'pivotal ci' },
      { iconKey: 'codefresh', defaultLabel: 'Codefresh', search: 'gitops kubernetes ci' },
      { iconKey: 'octopus_deploy', defaultLabel: 'Octopus Deploy', search: 'release deployment' },
      { iconKey: 'buddy_ci', defaultLabel: 'Buddy', search: 'automation pipeline' },
      { iconKey: 'semaphore_ci', defaultLabel: 'Semaphore CI', search: 'cloud ci' },
      { iconKey: 'tekton', defaultLabel: 'Tekton', search: 'kubernetes knative pipeline' },
      { iconKey: 'spinnaker', defaultLabel: 'Spinnaker', search: 'cd delivery netflix' },
      { iconKey: 'argo', defaultLabel: 'Argo CD / Workflows', search: 'gitops workflow kubernetes' },
      { iconKey: 'flux_cd', defaultLabel: 'Flux', search: 'gitops helm kubernetes' },
      { iconKey: 'jfrog_pipelines', defaultLabel: 'JFrog Pipelines', search: 'artifact ci' },
      { iconKey: 'jfrog', defaultLabel: 'JFrog Platform', search: 'artifactory xray' },
      { iconKey: 'dependabot', defaultLabel: 'Dependabot', search: 'dependencies pr github' },
      { iconKey: 'renovate', defaultLabel: 'Renovate', search: 'dependencies bot' },
      { iconKey: 'pre_commit', defaultLabel: 'pre-commit', search: 'hooks lint' },
      { iconKey: 'bitrise', defaultLabel: 'Bitrise', search: 'mobile ci' },
      { iconKey: 'fastlane', defaultLabel: 'Fastlane', search: 'ios android release' },
      { iconKey: 'xcode', defaultLabel: 'Xcode', search: 'apple ios build' },
      { iconKey: 'maven', defaultLabel: 'Maven', search: 'java build pom' },
      { iconKey: 'gradle', defaultLabel: 'Gradle', search: 'java kotlin build' },
      { iconKey: 'npm', defaultLabel: 'npm', search: 'node javascript package' },
      { iconKey: 'yarn', defaultLabel: 'Yarn', search: 'node package' },
      { iconKey: 'pnpm', defaultLabel: 'pnpm', search: 'node package' },
      { iconKey: 'jetbrains', defaultLabel: 'JetBrains', search: 'idea teamcity gateway' },
      { iconKey: 'awsdev_codebuild', defaultLabel: 'AWS CodeBuild', search: 'amazon ci' },
      { iconKey: 'awsdev_codepipeline', defaultLabel: 'AWS CodePipeline', search: 'amazon cd' },
      { iconKey: 'googlecloud', defaultLabel: 'Google Cloud Build', search: 'gcb gcp ci' },
      { iconKey: 'azure', defaultLabel: 'Azure DevOps / Pipelines', search: 'ado microsoft ci cd boards' },
      { iconKey: 'service', defaultLabel: 'Woodpecker CI', search: 'drone fork pipeline' },
    ],
  },
  {
    title: 'IaC & provisioning',
    items: [
      { iconKey: 'terraform', defaultLabel: 'Terraform', search: 'hashicorp hcl state' },
      { iconKey: 'opentofu', defaultLabel: 'OpenTofu', search: 'terraform fork oss' },
      { iconKey: 'pulumi', defaultLabel: 'Pulumi', search: 'typescript python go infrastructure code' },
      { iconKey: 'ansible', defaultLabel: 'Ansible', search: 'playbook automation red hat' },
      { iconKey: 'puppet', defaultLabel: 'Puppet', search: 'config management' },
      { iconKey: 'chef', defaultLabel: 'Chef', search: 'infra automation cookbook' },
      { iconKey: 'saltstack', defaultLabel: 'Salt / SaltStack', search: 'config management' },
      { iconKey: 'packer', defaultLabel: 'Packer', search: 'hashicorp image ami' },
      { iconKey: 'vault', defaultLabel: 'HashiCorp Vault', search: 'secrets kms' },
      { iconKey: 'consul', defaultLabel: 'HashiCorp Consul', search: 'service mesh discovery' },
      { iconKey: 'nomad', defaultLabel: 'HashiCorp Nomad', search: 'scheduler workloads' },
      { iconKey: 'vagrant', defaultLabel: 'Vagrant', search: 'hashicorp vm devbox' },
      { iconKey: 'helm', defaultLabel: 'Helm', search: 'kubernetes chart' },
      { iconKey: 'serverless_framework', defaultLabel: 'Serverless Framework', search: 'lambda faas yaml' },
      { iconKey: 'awsdev_cdk', defaultLabel: 'AWS CDK', search: 'cloud development kit typescript python' },
      { iconKey: 'awsgov_cloudformation', defaultLabel: 'AWS CloudFormation', search: 'cfn stack template yaml' },
      { iconKey: 'service', defaultLabel: 'Terragrunt', search: 'terraform wrapper dry modules' },
      { iconKey: 'service', defaultLabel: 'Atlantis', search: 'terraform pull request automation' },
      { iconKey: 'service', defaultLabel: 'Crossplane', search: 'kubernetes control plane crd' },
      { iconKey: 'service', defaultLabel: 'AWS SAM', search: 'serverless application model' },
    ],
  },
  {
    title: 'Testing, quality & security',
    items: [
      { iconKey: 'jest', defaultLabel: 'Jest', search: 'javascript unit test' },
      { iconKey: 'mocha', defaultLabel: 'Mocha', search: 'javascript test' },
      { iconKey: 'vitest', defaultLabel: 'Vitest', search: 'vite test' },
      { iconKey: 'cypress', defaultLabel: 'Cypress', search: 'e2e browser test' },
      { iconKey: 'selenium', defaultLabel: 'Selenium', search: 'browser automation' },
      { iconKey: 'eslint', defaultLabel: 'ESLint', search: 'javascript lint' },
      { iconKey: 'prettier', defaultLabel: 'Prettier', search: 'formatter code style' },
      { iconKey: 'swagger', defaultLabel: 'Swagger', search: 'openapi rest api' },
      { iconKey: 'openapi_initiative', defaultLabel: 'OpenAPI', search: 'swagger spec rest' },
      { iconKey: 'postman', defaultLabel: 'Postman', search: 'api client collection' },
      { iconKey: 'insomnia', defaultLabel: 'Insomnia', search: 'api client rest' },
      { iconKey: 'sonarqube', defaultLabel: 'SonarQube', search: 'sast quality gate' },
      { iconKey: 'codecov', defaultLabel: 'Codecov', search: 'coverage test' },
      { iconKey: 'snyk', defaultLabel: 'Snyk', search: 'vulnerability dependencies container' },
      { iconKey: 'trivy', defaultLabel: 'Trivy', search: 'container scan vulnerability' },
      { iconKey: 'falco', defaultLabel: 'Falco', search: 'runtime security kubernetes' },
    ],
  },
  {
    title: 'Monitoring & observability',
    items: [
      { iconKey: 'grafana', defaultLabel: 'Grafana', search: 'dashboards loki tempo' },
      { iconKey: 'prometheus', defaultLabel: 'Prometheus', search: 'metrics promql alertmanager' },
      { iconKey: 'datadog', defaultLabel: 'Datadog', search: 'apm logs rum' },
      { iconKey: 'newrelic', defaultLabel: 'New Relic', search: 'apm browser' },
      { iconKey: 'splunk', defaultLabel: 'Splunk', search: 'siem logs' },
      { iconKey: 'elastic', defaultLabel: 'Elastic', search: 'elk stack' },
      { iconKey: 'elasticsearch', defaultLabel: 'Elasticsearch', search: 'search logs' },
      { iconKey: 'kibana', defaultLabel: 'Kibana', search: 'elastic visualize' },
      { iconKey: 'sentry', defaultLabel: 'Sentry', search: 'errors apm frontend' },
      { iconKey: 'dynatrace', defaultLabel: 'Dynatrace', search: 'apm observability' },
      { iconKey: 'jaeger', defaultLabel: 'Jaeger', search: 'tracing opentelemetry' },
      { iconKey: 'opentelemetry', defaultLabel: 'OpenTelemetry', search: 'otel traces metrics logs' },
      { iconKey: 'thanos', defaultLabel: 'Thanos', search: 'prometheus long term' },
      { iconKey: 'fluentbit', defaultLabel: 'Fluent Bit', search: 'log forwarder' },
      { iconKey: 'fluentd', defaultLabel: 'Fluentd', search: 'log collector' },
      { iconKey: 'graylog', defaultLabel: 'Graylog', search: 'logs siem' },
      { iconKey: 'icinga', defaultLabel: 'Icinga', search: 'nagios monitoring' },
      { iconKey: 'checkmk', defaultLabel: 'Checkmk', search: 'monitoring nagios' },
      { iconKey: 'pingdom', defaultLabel: 'Pingdom', search: 'uptime http' },
      { iconKey: 'statuspage', defaultLabel: 'Atlassian Statuspage', search: 'incident comms' },
      { iconKey: 'uptime_kuma', defaultLabel: 'Uptime Kuma', search: 'self hosted uptime' },
      { iconKey: 'pagerduty', defaultLabel: 'PagerDuty', search: 'on call incident' },
      { iconKey: 'opsgenie', defaultLabel: 'Opsgenie', search: 'alert on call atlassian' },
      { iconKey: 'amazoncloudwatch', defaultLabel: 'Amazon CloudWatch', search: 'aws metrics logs alarms' },
    ],
  },
  {
    title: 'Containers & registries',
    items: [
      { iconKey: 'docker', defaultLabel: 'Docker', search: 'container image' },
      { iconKey: 'podman', defaultLabel: 'Podman', search: 'container oci rootless' },
      { iconKey: 'containerd', defaultLabel: 'containerd', search: 'cri runtime kubernetes' },
      { iconKey: 'harbor', defaultLabel: 'Harbor', search: 'registry oci scan' },
      { iconKey: 'sonatype', defaultLabel: 'Sonatype Nexus', search: 'repository maven npm' },
      { iconKey: 'artifacthub', defaultLabel: 'Artifact Hub', search: 'helm chart oci' },
      { iconKey: 'kubernetes', defaultLabel: 'Kubernetes', search: 'k8s cluster' },
      { iconKey: 'portainer', defaultLabel: 'Portainer', search: 'docker ui swarm' },
      { iconKey: 'rancher', defaultLabel: 'Rancher', search: 'kubernetes management' },
      { iconKey: 'envoy', defaultLabel: 'Envoy', search: 'proxy service mesh' },
      { iconKey: 'istio', defaultLabel: 'Istio', search: 'service mesh mtls' },
      { iconKey: 'linkerd', defaultLabel: 'Linkerd', search: 'service mesh' },
      { iconKey: 'cilium', defaultLabel: 'Cilium', search: 'ebpf network kubernetes' },
      { iconKey: 'traefik', defaultLabel: 'Traefik', search: 'ingress reverse proxy' },
      { iconKey: 'caddy', defaultLabel: 'Caddy', search: 'https reverse proxy' },
    ],
  },
  {
    title: 'Generic',
    items: [
      {
        iconKey: 'diagram_text',
        defaultLabel: 'Text note',
        nodeType: 'text',
        search: 'annotation caption label multiline type free floating',
      },
      {
        iconKey: 'diagram_text',
        defaultLabel: 'Risk',
        nodeType: 'text',
        noteTag: 'risk',
        search: 'risk warning alert',
      },
      {
        iconKey: 'diagram_text',
        defaultLabel: 'Question',
        nodeType: 'text',
        noteTag: 'question',
        search: 'question open issue',
      },
      {
        iconKey: 'diagram_text',
        defaultLabel: 'WIP',
        nodeType: 'text',
        noteTag: 'wip',
        search: 'work in progress draft',
      },
      { iconKey: 'service', defaultLabel: 'Service' },
      { iconKey: 'api', defaultLabel: 'REST / API' },
      { iconKey: 'queue', defaultLabel: 'Queue / worker' },
    ],
  },
];

/** @param {{ iconKey: string, defaultLabel: string, search?: string, noteTag?: string }} item */
export function paletteItemSearchText(item) {
  const spec = resolveIcon(item.iconKey);
  return [item.defaultLabel, item.iconKey, item.search, item.noteTag, spec.title]
    .filter(Boolean)
    .join(' ')
    .toLowerCase();
}

/** @returns {typeof PALETTE_GROUPS | null} null when query is empty (use full palette + local expand state) */
export function getFilteredPaletteGroups(query) {
  const terms = query
    .trim()
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean);
  if (terms.length === 0) return null;
  return PALETTE_GROUPS.map((g) => ({
    ...g,
    items: g.items.filter((item) => {
      const hay = paletteItemSearchText(item);
      return terms.every((t) => hay.includes(t));
    }),
  })).filter((g) => g.items.length > 0);
}
