import {
  siAmazonapigateway,
  siAmazoncloudwatch,
  siAmazoncognito,
  siAmazondocumentdb,
  siAmazondynamodb,
  siAmazonec2,
  siAmazonecs,
  siAmazoneks,
  siAmazonelasticache,
  siAmazoniam,
  siAmazonrds,
  siAmazonredshift,
  siAmazonroute53,
  siAmazons3,
  siAmazonsimpleemailservice,
  siAmazonsqs,
  siAmazonwebservices,
  siApachekafka,
  siApachespark,
  siAnthropic,
  siArgo,
  siAwsamplify,
  siAwselasticloadbalancing,
  siAwsfargate,
  siAwslambda,
  siAwsorganizations,
  siAwssecretsmanager,
  siCloudflare,
  siDatabricks,
  siDigitalocean,
  siDocker,
  siGrafana,
  siGooglecloud,
  siHelm,
  siHetzner,
  siHuggingface,
  siJupyter,
  siKeras,
  siKubernetes,
  siLangchain,
  siMlflow,
  siMongodb,
  siNeo4j,
  siNginx,
  siOllama,
  siOpenai,
  siPostgresql,
  siPrometheus,
  siPytorch,
  siRabbitmq,
  siRedis,
  siScaleway,
  siScikitlearn,
  siSnowflake,
  siTerraform,
  siTensorflow,
  siVercel,
} from 'simple-icons';

function fromSimple(icon) {
  return {
    kind: 'path',
    title: icon.title,
    hex: icon.hex,
    path: icon.path,
  };
}

/** Official resource artwork: https://github.com/kubernetes/community (Apache-2.0) */
function k8sResource(svgBasename, title) {
  return {
    kind: 'url',
    title,
    hex: '326CE5',
    url: `/icons/k8s/${svgBasename}.svg`,
  };
}

/** PNGs from https://github.com/awslabs/aws-icons-for-plantuml (Apache-2.0) */
const AWS_ARCH_ORANGE = 'FF9900';

function awsArchPng(dir, file) {
  return {
    kind: 'url',
    title: file,
    hex: AWS_ARCH_ORANGE,
    url: `/icons/aws-plantuml/${dir}/${file}.png`,
  };
}

/** @param {string} dir @param {Record<string, string>} keyToFilename */
function mapAwsArch(dir, keyToFilename) {
  const out = {};
  for (const [key, file] of Object.entries(keyToFilename)) {
    out[key] = awsArchPng(dir, file);
  }
  return out;
}

const AWS_AI_MAP = {
  awsai_bedrock: 'Bedrock',
  awsai_bedrock_agent_core: 'BedrockAgentCore',
  awsai_sagemaker: 'SageMakerAI',
  awsai_sagemaker_ground_truth: 'SageMakerGroundTruth',
  awsai_sagemaker_notebook: 'SageMakerAINotebook',
  awsai_comprehend: 'Comprehend',
  awsai_comprehend_medical: 'ComprehendMedical',
  awsai_rekognition: 'Rekognition',
  awsai_textract: 'Textract',
  awsai_lex: 'Lex',
  awsai_polly: 'Polly',
  awsai_transcribe: 'Transcribe',
  awsai_translate: 'Translate',
  awsai_kendra: 'Kendra',
  awsai_personalize: 'Personalize',
  awsai_forecast: 'Forecast',
  awsai_fraud_detector: 'FraudDetector',
  awsai_deep_racer: 'DeepRacer',
  awsai_augmented_ai: 'AugmentedAIA2I',
  awsai_panorama: 'Panorama',
  awsai_codeguru: 'CodeGuru',
  awsai_q: 'Q',
  awsai_nova: 'Nova',
  awsai_elastic_inference: 'ElasticInference',
  awsai_pytorch_on_aws: 'PyTorchonAWS',
  awsai_tensorflow_on_aws: 'TensorFlowonAWS',
  awsai_deep_learning_containers: 'DeepLearningContainers',
  awsai_deep_learning_amis: 'DeepLearningAMIs',
  awsai_devops_guru: 'DevOpsGuru',
  awsai_monitron: 'Monitron',
  awsai_lookout_equipment: 'LookoutforEquipment',
  awsai_lookout_vision: 'LookoutforVision',
  awsai_codewhisperer: 'CodeWhisperer',
  awsai_health_scribe: 'HealthScribe',
  awsai_neuron: 'Neuron',
};

const AWS_ANALYTICS_MAP = {
  awsana_athena: 'Athena',
  awsana_emr: 'EMR',
  awsana_glue: 'Glue',
  awsana_kinesis: 'Kinesis',
  awsana_opensearch: 'OpenSearchService',
  awsana_lake_formation: 'LakeFormation',
  awsana_firehose: 'DataFirehose',
  awsana_redshift_ml: 'RedshiftML',
  awsana_msk: 'ManagedStreamingforApacheKafka',
  awsana_flink: 'ManagedServiceforApacheFlink',
  awsana_glue_databrew: 'GlueDataBrew',
  awsana_entity_resolution: 'EntityResolution',
  awsana_finspace: 'FinSpace',
  awsana_datazone: 'DataZone',
  awsana_clean_rooms: 'CleanRooms',
  awsana_cloudsearch: 'CloudSearch',
};

const AWS_INTEGRATION_MAP = {
  awsint_eventbridge: 'EventBridge',
  awsint_step_functions: 'StepFunctions',
  awsint_sns: 'SimpleNotificationService',
  awsint_sqs: 'SimpleQueueService',
  awsint_appsync: 'AppSync',
  awsint_mwaa: 'ManagedWorkflowsforApacheAirflow',
  awsint_express_workflows: 'ExpressWorkflows',
};

/** Architecture PNGs — additional categories under public/icons/aws-plantuml/ */
const AWS_COMPUTE_MAP = {
  awscmp_apprunner: 'AppRunner',
  awscmp_batch: 'Batch',
  awscmp_ec2: 'EC2',
  awscmp_ec2_autoscaling: 'EC2AutoScaling',
  awscmp_ec2_spot: 'EC2SpotInstance',
  awscmp_elastic_beanstalk: 'ElasticBeanstalk',
  awscmp_lambda: 'Lambda',
  awscmp_lambda_function: 'LambdaLambdaFunction',
  awscmp_lightsail: 'Lightsail',
  awscmp_outposts: 'Outpostsfamily',
  awscmp_wavelength: 'Wavelength',
  awscmp_local_zones: 'LocalZones',
  awscmp_serverless_repo: 'ServerlessApplicationRepository',
  awscmp_parallel_cluster: 'ParallelCluster',
  awscmp_nitro_enclaves: 'NitroEnclaves',
  awscmp_simspace_weaver: 'SimSpaceWeaver',
};

const AWS_CONTAINERS_MAP = {
  awsctr_ecr: 'ElasticContainerRegistry',
  awsctr_ecs: 'ElasticContainerService',
  awsctr_eks: 'ElasticKubernetesService',
  awsctr_fargate_icon: 'Fargate',
  awsctr_eks_anywhere: 'EKSAnywhere',
  awsctr_ecs_anywhere: 'ECSAnywhere',
  awsctr_rosa: 'RedHatOpenShiftServiceonAWS',
};

const AWS_DATABASE_PLANT_MAP = {
  awsdbp_aurora: 'Aurora',
  awsdbp_rds: 'RDS',
  awsdbp_dynamodb: 'DynamoDB',
  awsdbp_elasticache: 'ElastiCache',
  awsdbp_documentdb: 'DocumentDB',
  awsdbp_neptune: 'Neptune',
  awsdbp_memorydb: 'MemoryDB',
  awsdbp_keyspaces: 'Keyspaces',
  awsdbp_dms: 'DatabaseMigrationService',
  awsdbp_timestream: 'Timestream',
};

const AWS_STORAGE_PLANT_MAP = {
  awsstor_s3: 'SimpleStorageService',
  awsstor_ebs: 'ElasticBlockStore',
  awsstor_efs: 'EFS',
  awsstor_fsx: 'FSx',
  awsstor_backup: 'Backup',
  awsstor_snowball: 'Snowball',
  awsstor_snowball_edge: 'SnowballEdge',
  awsstor_storage_gateway: 'StorageGateway',
};

const AWS_NETWORKING_MAP = {
  awsnet_cloudfront: 'CloudFront',
  awsnet_apigateway: 'APIGateway',
  awsnet_route53: 'Route53',
  awsnet_transit_gateway: 'TransitGateway',
  awsnet_direct_connect: 'DirectConnect',
  awsnet_global_accelerator: 'GlobalAccelerator',
  awsnet_private_link: 'PrivateLink',
  awsnet_app_mesh: 'AppMesh',
  awsnet_cloud_map: 'CloudMap',
  awsnet_client_vpn: 'ClientVPN',
  awsnet_site_to_site_vpn: 'SitetoSiteVPN',
  awsnet_alb: 'ElasticLoadBalancingApplicationLoadBalancer',
  awsnet_nlb: 'ElasticLoadBalancingNetworkLoadBalancer',
  awsnet_gwlb: 'ElasticLoadBalancingGatewayLoadBalancer',
};

const AWS_SECURITY_MAP = {
  awssec_iam: 'IdentityandAccessManagement',
  awssec_kms: 'KeyManagementService',
  awssec_waf: 'WAF',
  awssec_shield: 'Shield',
  awssec_guardduty: 'GuardDuty',
  awssec_security_hub: 'SecurityHub',
  awssec_macie: 'Macie',
  awssec_inspector: 'Inspector',
  awssec_acm: 'CertificateManager',
  awssec_secrets: 'SecretsManager',
  awssec_network_firewall: 'NetworkFirewall',
  awssec_firewall_manager: 'FirewallManager',
  awssec_iam_identity_center: 'IAMIdentityCenter',
  awssec_detective: 'Detective',
  awssec_security_lake: 'SecurityLake',
};

const AWS_MANAGEMENT_MAP = {
  awsgov_cloudformation: 'CloudFormation',
  awsgov_cloudtrail: 'CloudTrail',
  awsgov_cloudwatch: 'CloudWatch',
  awsgov_systems_manager: 'SystemsManager',
  awsgov_config: 'Config',
  awsgov_control_tower: 'ControlTower',
  awsgov_organizations: 'Organizations',
  awsgov_autoscaling: 'AutoScaling',
  awsgov_resource_explorer: 'ResourceExplorer',
  awsgov_service_catalog: 'ServiceCatalog',
  awsgov_health: 'HealthDashboard',
  awsgov_compute_optimizer: 'ComputeOptimizer',
};

const AWS_DEVELOPER_MAP = {
  awsdev_codebuild: 'CodeBuild',
  awsdev_codedeploy: 'CodeDeploy',
  awsdev_codepipeline: 'CodePipeline',
  awsdev_codecommit: 'CodeCommit',
  awsdev_codeartifact: 'CodeArtifact',
  awsdev_cloud9: 'Cloud9',
  awsdev_cloudshell: 'CloudShell',
  awsdev_xray: 'XRay',
  awsdev_cdk: 'CloudDevelopmentKit',
};

const AWS_MIGRATION_MAP = {
  awsmigr_datasync: 'DataSync',
  awsmigr_transfer_family: 'TransferFamily',
  awsmigr_mgn: 'ApplicationMigrationService',
  awsmigr_mainframe: 'MainframeModernization',
};

const AWS_QUANTUM_MAP = {
  aws_quantum_braket: 'Braket',
};

/** @typedef {{ kind: 'path', title: string, hex: string, path: string } | { kind: 'url', title: string, hex: string, url: string }} IconSpec */

/** @type {Record<string, IconSpec>} */
export const ICON_BY_KEY = {
  kubernetes: fromSimple(siKubernetes),
  k8s_pod: k8sResource('pod', 'Pod'),
  k8s_deploy: k8sResource('deploy', 'Deployment'),
  k8s_rs: k8sResource('rs', 'ReplicaSet'),
  k8s_sts: k8sResource('sts', 'StatefulSet'),
  k8s_ds: k8sResource('ds', 'DaemonSet'),
  k8s_job: k8sResource('job', 'Job'),
  k8s_cronjob: k8sResource('cronjob', 'CronJob'),
  k8s_svc: k8sResource('svc', 'Service'),
  k8s_ingress: k8sResource('ing', 'Ingress'),
  k8s_ep: k8sResource('ep', 'Endpoints'),
  k8s_pvc: k8sResource('pvc', 'PersistentVolumeClaim'),
  k8s_pv: k8sResource('pv', 'PersistentVolume'),
  k8s_sc: k8sResource('sc', 'StorageClass'),
  k8s_vol: k8sResource('vol', 'Volume'),
  k8s_cm: k8sResource('cm', 'ConfigMap'),
  k8s_secret: k8sResource('secret', 'Secret'),
  k8s_ns: k8sResource('ns', 'Namespace'),
  k8s_hpa: k8sResource('hpa', 'HorizontalPodAutoscaler'),
  k8s_netpol: k8sResource('netpol', 'NetworkPolicy'),
  k8s_role: k8sResource('role', 'Role'),
  k8s_crole: k8sResource('c-role', 'ClusterRole'),
  k8s_rb: k8sResource('rb', 'RoleBinding'),
  k8s_crb: k8sResource('crb', 'ClusterRoleBinding'),
  k8s_sa: k8sResource('sa', 'ServiceAccount'),
  k8s_quota: k8sResource('quota', 'ResourceQuota'),
  k8s_limits: k8sResource('limits', 'LimitRange'),
  k8s_crd: k8sResource('crd', 'CustomResourceDefinition'),
  docker: fromSimple(siDocker),
  helm: fromSimple(siHelm),
  argo: fromSimple(siArgo),
  terraform: fromSimple(siTerraform),
  amazoniam: fromSimple(siAmazoniam),
  amazoncognito: fromSimple(siAmazoncognito),
  amazondocumentdb: fromSimple(siAmazondocumentdb),
  amazonelasticache: fromSimple(siAmazonelasticache),
  amazonredshift: fromSimple(siAmazonredshift),
  amazonroute53: fromSimple(siAmazonroute53),
  amazon_ses: fromSimple(siAmazonsimpleemailservice),
  awsamplify: fromSimple(siAwsamplify),
  awselb: fromSimple(siAwselasticloadbalancing),
  awsfargate: fromSimple(siAwsfargate),
  awsorganizations: fromSimple(siAwsorganizations),
  awssecretsmanager: fromSimple(siAwssecretsmanager),
  tensorflow: fromSimple(siTensorflow),
  pytorch: fromSimple(siPytorch),
  huggingface: fromSimple(siHuggingface),
  jupyter: fromSimple(siJupyter),
  keras: fromSimple(siKeras),
  scikitlearn: fromSimple(siScikitlearn),
  mlflow: fromSimple(siMlflow),
  langchain: fromSimple(siLangchain),
  openai: fromSimple(siOpenai),
  anthropic: fromSimple(siAnthropic),
  ollama: fromSimple(siOllama),
  databricks: fromSimple(siDatabricks),
  apachespark: fromSimple(siApachespark),
  snowflake: fromSimple(siSnowflake),
  neo4j: fromSimple(siNeo4j),
  amazoneks: fromSimple(siAmazoneks),
  amazonec2: fromSimple(siAmazonec2),
  amazons3: fromSimple(siAmazons3),
  amazonrds: fromSimple(siAmazonrds),
  awslambda: fromSimple(siAwslambda),
  amazondynamodb: fromSimple(siAmazondynamodb),
  amazonapigateway: fromSimple(siAmazonapigateway),
  amazonsqs: fromSimple(siAmazonsqs),
  amazoncloudwatch: fromSimple(siAmazoncloudwatch),
  amazonwebservices: fromSimple(siAmazonwebservices),
  amazonecs: fromSimple(siAmazonecs),
  googlecloud: fromSimple(siGooglecloud),
  azure: {
    kind: 'url',
    title: 'Microsoft Azure',
    hex: '0078D4',
    url: '/icons/azure.svg',
  },
  cloudflare: fromSimple(siCloudflare),
  digitalocean: fromSimple(siDigitalocean),
  hetzner: fromSimple(siHetzner),
  scaleway: fromSimple(siScaleway),
  vercel: fromSimple(siVercel),
  postgresql: fromSimple(siPostgresql),
  redis: fromSimple(siRedis),
  mongodb: fromSimple(siMongodb),
  nginx: fromSimple(siNginx),
  rabbitmq: fromSimple(siRabbitmq),
  kafka: fromSimple(siApachekafka),
  grafana: fromSimple(siGrafana),
  prometheus: fromSimple(siPrometheus),
  service: {
    kind: 'path',
    title: 'Service',
    hex: '64748b',
    path: 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z',
  },
  api: {
    kind: 'path',
    title: 'API',
    hex: '6366f1',
    path: 'M8 5v14l11-7z',
  },
  queue: {
    kind: 'path',
    title: 'Queue',
    hex: 'd97706',
    path: 'M4 6h16v2H4zm0 5h16v2H4zm0 5h16v2H4z',
  },
  ...mapAwsArch('ArtificialIntelligence', AWS_AI_MAP),
  ...mapAwsArch('Analytics', AWS_ANALYTICS_MAP),
  ...mapAwsArch('ApplicationIntegration', AWS_INTEGRATION_MAP),
  ...mapAwsArch('Compute', AWS_COMPUTE_MAP),
  ...mapAwsArch('Containers', AWS_CONTAINERS_MAP),
  ...mapAwsArch('Database', AWS_DATABASE_PLANT_MAP),
  ...mapAwsArch('Storage', AWS_STORAGE_PLANT_MAP),
  ...mapAwsArch('NetworkingContentDelivery', AWS_NETWORKING_MAP),
  ...mapAwsArch('SecurityIdentityCompliance', AWS_SECURITY_MAP),
  ...mapAwsArch('ManagementGovernance', AWS_MANAGEMENT_MAP),
  ...mapAwsArch('DeveloperTools', AWS_DEVELOPER_MAP),
  ...mapAwsArch('MigrationModernization', AWS_MIGRATION_MAP),
  ...mapAwsArch('QuantumTechnologies', AWS_QUANTUM_MAP),
};

export const DEFAULT_ICON_KEY = 'service';

export function resolveIcon(iconKey) {
  return ICON_BY_KEY[iconKey] || ICON_BY_KEY[DEFAULT_ICON_KEY];
}

export const PALETTE_GROUPS = [
  {
    title: 'Kubernetes resources',
    items: [
      { iconKey: 'k8s_pod', defaultLabel: 'Pod' },
      { iconKey: 'k8s_deploy', defaultLabel: 'Deployment' },
      { iconKey: 'k8s_rs', defaultLabel: 'ReplicaSet' },
      { iconKey: 'k8s_sts', defaultLabel: 'StatefulSet' },
      { iconKey: 'k8s_ds', defaultLabel: 'DaemonSet' },
      { iconKey: 'k8s_job', defaultLabel: 'Job' },
      { iconKey: 'k8s_cronjob', defaultLabel: 'CronJob' },
      { iconKey: 'k8s_svc', defaultLabel: 'Service' },
      { iconKey: 'k8s_ingress', defaultLabel: 'Ingress' },
      { iconKey: 'k8s_ep', defaultLabel: 'Endpoints' },
      { iconKey: 'k8s_pvc', defaultLabel: 'PersistentVolumeClaim' },
      { iconKey: 'k8s_pv', defaultLabel: 'PersistentVolume' },
      { iconKey: 'k8s_sc', defaultLabel: 'StorageClass' },
      { iconKey: 'k8s_vol', defaultLabel: 'Volume' },
      { iconKey: 'k8s_cm', defaultLabel: 'ConfigMap' },
      { iconKey: 'k8s_secret', defaultLabel: 'Secret' },
      { iconKey: 'k8s_ns', defaultLabel: 'Namespace' },
      { iconKey: 'k8s_hpa', defaultLabel: 'HorizontalPodAutoscaler' },
      { iconKey: 'k8s_netpol', defaultLabel: 'NetworkPolicy' },
      { iconKey: 'k8s_role', defaultLabel: 'Role' },
      { iconKey: 'k8s_crole', defaultLabel: 'ClusterRole' },
      { iconKey: 'k8s_rb', defaultLabel: 'RoleBinding' },
      { iconKey: 'k8s_crb', defaultLabel: 'ClusterRoleBinding' },
      { iconKey: 'k8s_sa', defaultLabel: 'ServiceAccount' },
      { iconKey: 'k8s_quota', defaultLabel: 'ResourceQuota' },
      { iconKey: 'k8s_limits', defaultLabel: 'LimitRange' },
      { iconKey: 'k8s_crd', defaultLabel: 'CustomResourceDefinition' },
    ],
  },
  {
    title: 'Kubernetes & delivery',
    items: [
      { iconKey: 'kubernetes', defaultLabel: 'Kubernetes cluster' },
      { iconKey: 'docker', defaultLabel: 'Container' },
      { iconKey: 'helm', defaultLabel: 'Helm release' },
      { iconKey: 'argo', defaultLabel: 'Argo CD' },
      { iconKey: 'terraform', defaultLabel: 'Terraform' },
    ],
  },
  {
    title: 'AWS',
    items: [
      { iconKey: 'amazonwebservices', defaultLabel: 'AWS account' },
      { iconKey: 'amazoniam', defaultLabel: 'IAM' },
      { iconKey: 'awsorganizations', defaultLabel: 'Organizations' },
      { iconKey: 'amazoneks', defaultLabel: 'EKS' },
      { iconKey: 'amazonecs', defaultLabel: 'ECS' },
      { iconKey: 'awsfargate', defaultLabel: 'Fargate' },
      { iconKey: 'amazonec2', defaultLabel: 'EC2' },
      { iconKey: 'awselb', defaultLabel: 'Elastic Load Balancing' },
      { iconKey: 'amazons3', defaultLabel: 'S3' },
      { iconKey: 'amazonrds', defaultLabel: 'RDS' },
      { iconKey: 'amazonredshift', defaultLabel: 'Redshift' },
      { iconKey: 'amazondynamodb', defaultLabel: 'DynamoDB' },
      { iconKey: 'amazondocumentdb', defaultLabel: 'DocumentDB' },
      { iconKey: 'amazonelasticache', defaultLabel: 'ElastiCache' },
      { iconKey: 'awslambda', defaultLabel: 'Lambda' },
      { iconKey: 'amazonapigateway', defaultLabel: 'API Gateway' },
      { iconKey: 'amazonsqs', defaultLabel: 'SQS' },
      { iconKey: 'amazonroute53', defaultLabel: 'Route 53' },
      { iconKey: 'amazoncloudwatch', defaultLabel: 'CloudWatch' },
      { iconKey: 'awssecretsmanager', defaultLabel: 'Secrets Manager' },
      { iconKey: 'amazoncognito', defaultLabel: 'Cognito' },
      { iconKey: 'amazon_ses', defaultLabel: 'SES' },
      { iconKey: 'awsamplify', defaultLabel: 'Amplify' },
    ],
  },
  {
    title: 'AWS AI & machine learning',
    items: [
      { iconKey: 'awsai_bedrock', defaultLabel: 'Amazon Bedrock' },
      { iconKey: 'awsai_bedrock_agent_core', defaultLabel: 'Bedrock Agent Core' },
      { iconKey: 'awsai_sagemaker', defaultLabel: 'Amazon SageMaker' },
      { iconKey: 'awsai_sagemaker_ground_truth', defaultLabel: 'SageMaker Ground Truth' },
      { iconKey: 'awsai_sagemaker_notebook', defaultLabel: 'SageMaker Notebook' },
      { iconKey: 'awsai_comprehend', defaultLabel: 'Amazon Comprehend' },
      { iconKey: 'awsai_comprehend_medical', defaultLabel: 'Comprehend Medical' },
      { iconKey: 'awsai_rekognition', defaultLabel: 'Amazon Rekognition' },
      { iconKey: 'awsai_textract', defaultLabel: 'Amazon Textract' },
      { iconKey: 'awsai_lex', defaultLabel: 'Amazon Lex' },
      { iconKey: 'awsai_polly', defaultLabel: 'Amazon Polly' },
      { iconKey: 'awsai_transcribe', defaultLabel: 'Amazon Transcribe' },
      { iconKey: 'awsai_translate', defaultLabel: 'Amazon Translate' },
      { iconKey: 'awsai_kendra', defaultLabel: 'Amazon Kendra' },
      { iconKey: 'awsai_personalize', defaultLabel: 'Amazon Personalize' },
      { iconKey: 'awsai_forecast', defaultLabel: 'Amazon Forecast' },
      { iconKey: 'awsai_fraud_detector', defaultLabel: 'Amazon Fraud Detector' },
      { iconKey: 'awsai_deep_racer', defaultLabel: 'AWS DeepRacer' },
      { iconKey: 'awsai_augmented_ai', defaultLabel: 'Amazon Augmented AI' },
      { iconKey: 'awsai_panorama', defaultLabel: 'AWS Panorama' },
      { iconKey: 'awsai_codeguru', defaultLabel: 'Amazon CodeGuru' },
      { iconKey: 'awsai_q', defaultLabel: 'Amazon Q' },
      { iconKey: 'awsai_nova', defaultLabel: 'Amazon Nova' },
      { iconKey: 'awsai_elastic_inference', defaultLabel: 'Elastic Inference' },
      { iconKey: 'awsai_pytorch_on_aws', defaultLabel: 'PyTorch on AWS' },
      { iconKey: 'awsai_tensorflow_on_aws', defaultLabel: 'TensorFlow on AWS' },
      { iconKey: 'awsai_deep_learning_containers', defaultLabel: 'Deep Learning Containers' },
      { iconKey: 'awsai_deep_learning_amis', defaultLabel: 'Deep Learning AMIs' },
      { iconKey: 'awsai_devops_guru', defaultLabel: 'DevOps Guru' },
      { iconKey: 'awsai_monitron', defaultLabel: 'Amazon Monitron' },
      { iconKey: 'awsai_lookout_equipment', defaultLabel: 'Lookout for Equipment' },
      { iconKey: 'awsai_lookout_vision', defaultLabel: 'Lookout for Vision' },
      { iconKey: 'awsai_codewhisperer', defaultLabel: 'CodeWhisperer' },
      { iconKey: 'awsai_health_scribe', defaultLabel: 'AWS HealthScribe' },
      { iconKey: 'awsai_neuron', defaultLabel: 'AWS Neuron' },
    ],
  },
  {
    title: 'AWS analytics & streaming',
    items: [
      { iconKey: 'awsana_athena', defaultLabel: 'Amazon Athena' },
      { iconKey: 'awsana_emr', defaultLabel: 'Amazon EMR' },
      { iconKey: 'awsana_glue', defaultLabel: 'AWS Glue' },
      { iconKey: 'awsana_glue_databrew', defaultLabel: 'Glue DataBrew' },
      { iconKey: 'awsana_kinesis', defaultLabel: 'Amazon Kinesis' },
      { iconKey: 'awsana_firehose', defaultLabel: 'Kinesis Data Firehose' },
      { iconKey: 'awsana_opensearch', defaultLabel: 'Amazon OpenSearch' },
      { iconKey: 'awsana_lake_formation', defaultLabel: 'Lake Formation' },
      { iconKey: 'awsana_redshift_ml', defaultLabel: 'Redshift ML' },
      { iconKey: 'awsana_msk', defaultLabel: 'Amazon MSK' },
      { iconKey: 'awsana_flink', defaultLabel: 'Managed Apache Flink' },
      { iconKey: 'awsana_entity_resolution', defaultLabel: 'Entity Resolution' },
      { iconKey: 'awsana_finspace', defaultLabel: 'Amazon FinSpace' },
      { iconKey: 'awsana_datazone', defaultLabel: 'Amazon DataZone' },
      { iconKey: 'awsana_clean_rooms', defaultLabel: 'AWS Clean Rooms' },
      { iconKey: 'awsana_cloudsearch', defaultLabel: 'Amazon CloudSearch' },
    ],
  },
  {
    title: 'AWS integration & workflows',
    items: [
      { iconKey: 'awsint_eventbridge', defaultLabel: 'EventBridge' },
      { iconKey: 'awsint_step_functions', defaultLabel: 'Step Functions' },
      { iconKey: 'awsint_express_workflows', defaultLabel: 'Express Workflows' },
      { iconKey: 'awsint_sns', defaultLabel: 'Amazon SNS' },
      { iconKey: 'awsint_sqs', defaultLabel: 'Amazon SQS' },
      { iconKey: 'awsint_appsync', defaultLabel: 'AWS AppSync' },
      { iconKey: 'awsint_mwaa', defaultLabel: 'Amazon MWAA' },
    ],
  },
  {
    title: 'AWS compute & serverless',
    items: [
      { iconKey: 'awscmp_apprunner', defaultLabel: 'App Runner' },
      { iconKey: 'awscmp_batch', defaultLabel: 'AWS Batch' },
      { iconKey: 'awscmp_ec2', defaultLabel: 'EC2' },
      { iconKey: 'awscmp_ec2_autoscaling', defaultLabel: 'EC2 Auto Scaling' },
      { iconKey: 'awscmp_ec2_spot', defaultLabel: 'EC2 Spot' },
      { iconKey: 'awscmp_elastic_beanstalk', defaultLabel: 'Elastic Beanstalk' },
      { iconKey: 'awscmp_lambda', defaultLabel: 'Lambda' },
      { iconKey: 'awscmp_lambda_function', defaultLabel: 'Lambda function' },
      { iconKey: 'awscmp_lightsail', defaultLabel: 'Lightsail' },
      { iconKey: 'awscmp_outposts', defaultLabel: 'Outposts' },
      { iconKey: 'awscmp_wavelength', defaultLabel: 'Wavelength' },
      { iconKey: 'awscmp_local_zones', defaultLabel: 'Local Zones' },
      { iconKey: 'awscmp_serverless_repo', defaultLabel: 'Serverless App Repository' },
      { iconKey: 'awscmp_parallel_cluster', defaultLabel: 'ParallelCluster' },
      { iconKey: 'awscmp_nitro_enclaves', defaultLabel: 'Nitro Enclaves' },
      { iconKey: 'awscmp_simspace_weaver', defaultLabel: 'SimSpace Weaver' },
    ],
  },
  {
    title: 'AWS containers & Kubernetes',
    items: [
      { iconKey: 'awsctr_ecr', defaultLabel: 'ECR' },
      { iconKey: 'awsctr_ecs', defaultLabel: 'ECS' },
      { iconKey: 'awsctr_eks', defaultLabel: 'EKS' },
      { iconKey: 'awsctr_fargate_icon', defaultLabel: 'Fargate' },
      { iconKey: 'awsctr_eks_anywhere', defaultLabel: 'EKS Anywhere' },
      { iconKey: 'awsctr_ecs_anywhere', defaultLabel: 'ECS Anywhere' },
      { iconKey: 'awsctr_rosa', defaultLabel: 'ROSA' },
    ],
  },
  {
    title: 'AWS databases',
    items: [
      { iconKey: 'awsdbp_aurora', defaultLabel: 'Aurora' },
      { iconKey: 'awsdbp_rds', defaultLabel: 'RDS' },
      { iconKey: 'awsdbp_dynamodb', defaultLabel: 'DynamoDB' },
      { iconKey: 'awsdbp_elasticache', defaultLabel: 'ElastiCache' },
      { iconKey: 'awsdbp_documentdb', defaultLabel: 'DocumentDB' },
      { iconKey: 'awsdbp_neptune', defaultLabel: 'Neptune' },
      { iconKey: 'awsdbp_memorydb', defaultLabel: 'MemoryDB' },
      { iconKey: 'awsdbp_keyspaces', defaultLabel: 'Keyspaces' },
      { iconKey: 'awsdbp_dms', defaultLabel: 'Database Migration Service' },
      { iconKey: 'awsdbp_timestream', defaultLabel: 'Timestream' },
    ],
  },
  {
    title: 'AWS storage & backup',
    items: [
      { iconKey: 'awsstor_s3', defaultLabel: 'S3' },
      { iconKey: 'awsstor_ebs', defaultLabel: 'EBS' },
      { iconKey: 'awsstor_efs', defaultLabel: 'EFS' },
      { iconKey: 'awsstor_fsx', defaultLabel: 'FSx' },
      { iconKey: 'awsstor_backup', defaultLabel: 'AWS Backup' },
      { iconKey: 'awsstor_snowball', defaultLabel: 'Snowball' },
      { iconKey: 'awsstor_snowball_edge', defaultLabel: 'Snowball Edge' },
      { iconKey: 'awsstor_storage_gateway', defaultLabel: 'Storage Gateway' },
    ],
  },
  {
    title: 'AWS networking & CDN',
    items: [
      { iconKey: 'awsnet_cloudfront', defaultLabel: 'CloudFront' },
      { iconKey: 'awsnet_apigateway', defaultLabel: 'API Gateway' },
      { iconKey: 'awsnet_route53', defaultLabel: 'Route 53' },
      { iconKey: 'awsnet_transit_gateway', defaultLabel: 'Transit Gateway' },
      { iconKey: 'awsnet_direct_connect', defaultLabel: 'Direct Connect' },
      { iconKey: 'awsnet_global_accelerator', defaultLabel: 'Global Accelerator' },
      { iconKey: 'awsnet_private_link', defaultLabel: 'PrivateLink' },
      { iconKey: 'awsnet_app_mesh', defaultLabel: 'App Mesh' },
      { iconKey: 'awsnet_cloud_map', defaultLabel: 'Cloud Map' },
      { iconKey: 'awsnet_client_vpn', defaultLabel: 'Client VPN' },
      { iconKey: 'awsnet_site_to_site_vpn', defaultLabel: 'Site-to-Site VPN' },
      { iconKey: 'awsnet_alb', defaultLabel: 'Application Load Balancer' },
      { iconKey: 'awsnet_nlb', defaultLabel: 'Network Load Balancer' },
      { iconKey: 'awsnet_gwlb', defaultLabel: 'Gateway Load Balancer' },
      { iconKey: 'awssec_network_firewall', defaultLabel: 'Network Firewall' },
    ],
  },
  {
    title: 'AWS security & compliance',
    items: [
      { iconKey: 'awssec_iam', defaultLabel: 'IAM' },
      { iconKey: 'awssec_kms', defaultLabel: 'KMS' },
      { iconKey: 'awssec_waf', defaultLabel: 'WAF' },
      { iconKey: 'awssec_shield', defaultLabel: 'Shield' },
      { iconKey: 'awssec_guardduty', defaultLabel: 'GuardDuty' },
      { iconKey: 'awssec_security_hub', defaultLabel: 'Security Hub' },
      { iconKey: 'awssec_macie', defaultLabel: 'Macie' },
      { iconKey: 'awssec_inspector', defaultLabel: 'Inspector' },
      { iconKey: 'awssec_acm', defaultLabel: 'Certificate Manager' },
      { iconKey: 'awssec_secrets', defaultLabel: 'Secrets Manager' },
      { iconKey: 'awssec_network_firewall', defaultLabel: 'Network Firewall' },
      { iconKey: 'awssec_firewall_manager', defaultLabel: 'Firewall Manager' },
      { iconKey: 'awssec_iam_identity_center', defaultLabel: 'IAM Identity Center' },
      { iconKey: 'awssec_detective', defaultLabel: 'Detective' },
      { iconKey: 'awssec_security_lake', defaultLabel: 'Security Lake' },
    ],
  },
  {
    title: 'AWS management & governance',
    items: [
      { iconKey: 'awsgov_cloudformation', defaultLabel: 'CloudFormation' },
      { iconKey: 'awsgov_cloudtrail', defaultLabel: 'CloudTrail' },
      { iconKey: 'awsgov_cloudwatch', defaultLabel: 'CloudWatch' },
      { iconKey: 'awsgov_systems_manager', defaultLabel: 'Systems Manager' },
      { iconKey: 'awsgov_config', defaultLabel: 'AWS Config' },
      { iconKey: 'awsgov_control_tower', defaultLabel: 'Control Tower' },
      { iconKey: 'awsgov_organizations', defaultLabel: 'Organizations' },
      { iconKey: 'awsgov_autoscaling', defaultLabel: 'Auto Scaling' },
      { iconKey: 'awsgov_resource_explorer', defaultLabel: 'Resource Explorer' },
      { iconKey: 'awsgov_service_catalog', defaultLabel: 'Service Catalog' },
      { iconKey: 'awsgov_health', defaultLabel: 'Health Dashboard' },
      { iconKey: 'awsgov_compute_optimizer', defaultLabel: 'Compute Optimizer' },
    ],
  },
  {
    title: 'AWS developer & CI/CD',
    items: [
      { iconKey: 'awsdev_codebuild', defaultLabel: 'CodeBuild' },
      { iconKey: 'awsdev_codedeploy', defaultLabel: 'CodeDeploy' },
      { iconKey: 'awsdev_codepipeline', defaultLabel: 'CodePipeline' },
      { iconKey: 'awsdev_codecommit', defaultLabel: 'CodeCommit' },
      { iconKey: 'awsdev_codeartifact', defaultLabel: 'CodeArtifact' },
      { iconKey: 'awsdev_cloud9', defaultLabel: 'Cloud9' },
      { iconKey: 'awsdev_cloudshell', defaultLabel: 'CloudShell' },
      { iconKey: 'awsdev_xray', defaultLabel: 'X-Ray' },
      { iconKey: 'awsdev_cdk', defaultLabel: 'CDK' },
    ],
  },
  {
    title: 'AWS migration & transfer',
    items: [
      { iconKey: 'awsmigr_datasync', defaultLabel: 'DataSync' },
      { iconKey: 'awsmigr_transfer_family', defaultLabel: 'Transfer Family' },
      { iconKey: 'awsmigr_mgn', defaultLabel: 'Application Migration (MGN)' },
      { iconKey: 'awsmigr_mainframe', defaultLabel: 'Mainframe Modernization' },
    ],
  },
  {
    title: 'AWS quantum',
    items: [{ iconKey: 'aws_quantum_braket', defaultLabel: 'Braket' }],
  },
  {
    title: 'ML & AI ecosystem',
    items: [
      { iconKey: 'tensorflow', defaultLabel: 'TensorFlow' },
      { iconKey: 'pytorch', defaultLabel: 'PyTorch' },
      { iconKey: 'huggingface', defaultLabel: 'Hugging Face' },
      { iconKey: 'jupyter', defaultLabel: 'Jupyter' },
      { iconKey: 'keras', defaultLabel: 'Keras' },
      { iconKey: 'scikitlearn', defaultLabel: 'scikit-learn' },
      { iconKey: 'mlflow', defaultLabel: 'MLflow' },
      { iconKey: 'langchain', defaultLabel: 'LangChain' },
      { iconKey: 'openai', defaultLabel: 'OpenAI' },
      { iconKey: 'anthropic', defaultLabel: 'Anthropic' },
      { iconKey: 'ollama', defaultLabel: 'Ollama' },
      { iconKey: 'databricks', defaultLabel: 'Databricks' },
      { iconKey: 'apachespark', defaultLabel: 'Apache Spark' },
      { iconKey: 'snowflake', defaultLabel: 'Snowflake' },
      { iconKey: 'neo4j', defaultLabel: 'Neo4j' },
    ],
  },
  {
    title: 'Microsoft Azure',
    items: [
      { iconKey: 'azure', defaultLabel: 'Azure subscription' },
      { iconKey: 'azure', defaultLabel: 'Azure AKS' },
      { iconKey: 'azure', defaultLabel: 'Azure Functions' },
      { iconKey: 'azure', defaultLabel: 'Azure App Service' },
      { iconKey: 'azure', defaultLabel: 'Azure API Management' },
      { iconKey: 'azure', defaultLabel: 'Azure SQL' },
      { iconKey: 'azure', defaultLabel: 'Azure Cosmos DB' },
      { iconKey: 'azure', defaultLabel: 'Azure Storage' },
      { iconKey: 'azure', defaultLabel: 'Azure Key Vault' },
      { iconKey: 'azure', defaultLabel: 'Azure Service Bus' },
      { iconKey: 'azure', defaultLabel: 'Azure Event Hubs' },
      { iconKey: 'azure', defaultLabel: 'Azure Monitor' },
      { iconKey: 'azure', defaultLabel: 'Azure Container Apps' },
    ],
  },
  {
    title: 'Cloud providers',
    items: [
      { iconKey: 'googlecloud', defaultLabel: 'Google Cloud' },
      { iconKey: 'cloudflare', defaultLabel: 'Cloudflare' },
      { iconKey: 'digitalocean', defaultLabel: 'DigitalOcean' },
      { iconKey: 'hetzner', defaultLabel: 'Hetzner' },
      { iconKey: 'scaleway', defaultLabel: 'Scaleway' },
      { iconKey: 'vercel', defaultLabel: 'Vercel' },
    ],
  },
  {
    title: 'Data & messaging',
    items: [
      { iconKey: 'postgresql', defaultLabel: 'PostgreSQL' },
      { iconKey: 'redis', defaultLabel: 'Redis' },
      { iconKey: 'mongodb', defaultLabel: 'MongoDB' },
      { iconKey: 'rabbitmq', defaultLabel: 'RabbitMQ' },
      { iconKey: 'kafka', defaultLabel: 'Kafka' },
      { iconKey: 'nginx', defaultLabel: 'NGINX' },
    ],
  },
  {
    title: 'Observability',
    items: [
      { iconKey: 'grafana', defaultLabel: 'Grafana' },
      { iconKey: 'prometheus', defaultLabel: 'Prometheus' },
    ],
  },
  {
    title: 'Generic',
    items: [
      { iconKey: 'service', defaultLabel: 'Service' },
      { iconKey: 'api', defaultLabel: 'REST / API' },
      { iconKey: 'queue', defaultLabel: 'Queue / worker' },
    ],
  },
];
