import {
  siAmazonapigateway,
  siAmazoncloudwatch,
  siAmazondynamodb,
  siAmazonec2,
  siAmazonecs,
  siAmazoneks,
  siAmazonrds,
  siAmazons3,
  siAmazonsqs,
  siAmazonwebservices,
  siApachekafka,
  siArgo,
  siAwslambda,
  siCloudflare,
  siDigitalocean,
  siDocker,
  siGrafana,
  siGooglecloud,
  siHelm,
  siHetzner,
  siKubernetes,
  siMongodb,
  siNginx,
  siPostgresql,
  siPrometheus,
  siRabbitmq,
  siRedis,
  siScaleway,
  siTerraform,
  siVercel,
} from 'simple-icons';

function fromSimple(icon) {
  return {
    kind: 'path',
    title: icon.title,
    hex: icon.hex,
    path: icon.path,
  };
}

/** Official resource artwork: https://github.com/kubernetes/community (Apache-2.0) */
function k8sResource(svgBasename, title) {
  return {
    kind: 'url',
    title,
    hex: '326CE5',
    url: `/icons/k8s/${svgBasename}.svg`,
  };
}

/** @typedef {{ kind: 'path', title: string, hex: string, path: string } | { kind: 'url', title: string, hex: string, url: string }} IconSpec */

/** @type {Record<string, IconSpec>} */
export const ICON_BY_KEY = {
  kubernetes: fromSimple(siKubernetes),
  k8s_pod: k8sResource('pod', 'Pod'),
  k8s_deploy: k8sResource('deploy', 'Deployment'),
  k8s_rs: k8sResource('rs', 'ReplicaSet'),
  k8s_sts: k8sResource('sts', 'StatefulSet'),
  k8s_ds: k8sResource('ds', 'DaemonSet'),
  k8s_job: k8sResource('job', 'Job'),
  k8s_cronjob: k8sResource('cronjob', 'CronJob'),
  k8s_svc: k8sResource('svc', 'Service'),
  k8s_ingress: k8sResource('ing', 'Ingress'),
  k8s_ep: k8sResource('ep', 'Endpoints'),
  k8s_pvc: k8sResource('pvc', 'PersistentVolumeClaim'),
  k8s_pv: k8sResource('pv', 'PersistentVolume'),
  k8s_sc: k8sResource('sc', 'StorageClass'),
  k8s_vol: k8sResource('vol', 'Volume'),
  k8s_cm: k8sResource('cm', 'ConfigMap'),
  k8s_secret: k8sResource('secret', 'Secret'),
  k8s_ns: k8sResource('ns', 'Namespace'),
  k8s_hpa: k8sResource('hpa', 'HorizontalPodAutoscaler'),
  k8s_netpol: k8sResource('netpol', 'NetworkPolicy'),
  k8s_role: k8sResource('role', 'Role'),
  k8s_crole: k8sResource('c-role', 'ClusterRole'),
  k8s_rb: k8sResource('rb', 'RoleBinding'),
  k8s_crb: k8sResource('crb', 'ClusterRoleBinding'),
  k8s_sa: k8sResource('sa', 'ServiceAccount'),
  k8s_quota: k8sResource('quota', 'ResourceQuota'),
  k8s_limits: k8sResource('limits', 'LimitRange'),
  k8s_crd: k8sResource('crd', 'CustomResourceDefinition'),
  docker: fromSimple(siDocker),
  helm: fromSimple(siHelm),
  argo: fromSimple(siArgo),
  terraform: fromSimple(siTerraform),
  amazoneks: fromSimple(siAmazoneks),
  amazonec2: fromSimple(siAmazonec2),
  amazons3: fromSimple(siAmazons3),
  amazonrds: fromSimple(siAmazonrds),
  awslambda: fromSimple(siAwslambda),
  amazondynamodb: fromSimple(siAmazondynamodb),
  amazonapigateway: fromSimple(siAmazonapigateway),
  amazonsqs: fromSimple(siAmazonsqs),
  amazoncloudwatch: fromSimple(siAmazoncloudwatch),
  amazonwebservices: fromSimple(siAmazonwebservices),
  amazonecs: fromSimple(siAmazonecs),
  googlecloud: fromSimple(siGooglecloud),
  azure: {
    kind: 'url',
    title: 'Microsoft Azure',
    hex: '0078D4',
    url: '/icons/azure.svg',
  },
  cloudflare: fromSimple(siCloudflare),
  digitalocean: fromSimple(siDigitalocean),
  hetzner: fromSimple(siHetzner),
  scaleway: fromSimple(siScaleway),
  vercel: fromSimple(siVercel),
  postgresql: fromSimple(siPostgresql),
  redis: fromSimple(siRedis),
  mongodb: fromSimple(siMongodb),
  nginx: fromSimple(siNginx),
  rabbitmq: fromSimple(siRabbitmq),
  kafka: fromSimple(siApachekafka),
  grafana: fromSimple(siGrafana),
  prometheus: fromSimple(siPrometheus),
  service: {
    kind: 'path',
    title: 'Service',
    hex: '64748b',
    path: 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z',
  },
  api: {
    kind: 'path',
    title: 'API',
    hex: '6366f1',
    path: 'M8 5v14l11-7z',
  },
  queue: {
    kind: 'path',
    title: 'Queue',
    hex: 'd97706',
    path: 'M4 6h16v2H4zm0 5h16v2H4zm0 5h16v2H4z',
  },
};

export const DEFAULT_ICON_KEY = 'service';

export function resolveIcon(iconKey) {
  return ICON_BY_KEY[iconKey] || ICON_BY_KEY[DEFAULT_ICON_KEY];
}

export const PALETTE_GROUPS = [
  {
    title: 'Kubernetes resources',
    items: [
      { iconKey: 'k8s_pod', defaultLabel: 'Pod' },
      { iconKey: 'k8s_deploy', defaultLabel: 'Deployment' },
      { iconKey: 'k8s_rs', defaultLabel: 'ReplicaSet' },
      { iconKey: 'k8s_sts', defaultLabel: 'StatefulSet' },
      { iconKey: 'k8s_ds', defaultLabel: 'DaemonSet' },
      { iconKey: 'k8s_job', defaultLabel: 'Job' },
      { iconKey: 'k8s_cronjob', defaultLabel: 'CronJob' },
      { iconKey: 'k8s_svc', defaultLabel: 'Service' },
      { iconKey: 'k8s_ingress', defaultLabel: 'Ingress' },
      { iconKey: 'k8s_ep', defaultLabel: 'Endpoints' },
      { iconKey: 'k8s_pvc', defaultLabel: 'PersistentVolumeClaim' },
      { iconKey: 'k8s_pv', defaultLabel: 'PersistentVolume' },
      { iconKey: 'k8s_sc', defaultLabel: 'StorageClass' },
      { iconKey: 'k8s_vol', defaultLabel: 'Volume' },
      { iconKey: 'k8s_cm', defaultLabel: 'ConfigMap' },
      { iconKey: 'k8s_secret', defaultLabel: 'Secret' },
      { iconKey: 'k8s_ns', defaultLabel: 'Namespace' },
      { iconKey: 'k8s_hpa', defaultLabel: 'HorizontalPodAutoscaler' },
      { iconKey: 'k8s_netpol', defaultLabel: 'NetworkPolicy' },
      { iconKey: 'k8s_role', defaultLabel: 'Role' },
      { iconKey: 'k8s_crole', defaultLabel: 'ClusterRole' },
      { iconKey: 'k8s_rb', defaultLabel: 'RoleBinding' },
      { iconKey: 'k8s_crb', defaultLabel: 'ClusterRoleBinding' },
      { iconKey: 'k8s_sa', defaultLabel: 'ServiceAccount' },
      { iconKey: 'k8s_quota', defaultLabel: 'ResourceQuota' },
      { iconKey: 'k8s_limits', defaultLabel: 'LimitRange' },
      { iconKey: 'k8s_crd', defaultLabel: 'CustomResourceDefinition' },
    ],
  },
  {
    title: 'Kubernetes & delivery',
    items: [
      { iconKey: 'kubernetes', defaultLabel: 'Kubernetes cluster' },
      { iconKey: 'docker', defaultLabel: 'Container' },
      { iconKey: 'helm', defaultLabel: 'Helm release' },
      { iconKey: 'argo', defaultLabel: 'Argo CD' },
      { iconKey: 'terraform', defaultLabel: 'Terraform' },
    ],
  },
  {
    title: 'AWS',
    items: [
      { iconKey: 'amazonwebservices', defaultLabel: 'AWS account' },
      { iconKey: 'amazoneks', defaultLabel: 'EKS' },
      { iconKey: 'amazonecs', defaultLabel: 'ECS' },
      { iconKey: 'amazonec2', defaultLabel: 'EC2' },
      { iconKey: 'amazons3', defaultLabel: 'S3' },
      { iconKey: 'amazonrds', defaultLabel: 'RDS' },
      { iconKey: 'awslambda', defaultLabel: 'Lambda' },
      { iconKey: 'amazondynamodb', defaultLabel: 'DynamoDB' },
      { iconKey: 'amazonapigateway', defaultLabel: 'API Gateway' },
      { iconKey: 'amazonsqs', defaultLabel: 'SQS' },
      { iconKey: 'amazoncloudwatch', defaultLabel: 'CloudWatch' },
    ],
  },
  {
    title: 'Microsoft Azure',
    items: [
      { iconKey: 'azure', defaultLabel: 'Azure subscription' },
      { iconKey: 'azure', defaultLabel: 'Azure AKS' },
      { iconKey: 'azure', defaultLabel: 'Azure Functions' },
      { iconKey: 'azure', defaultLabel: 'Azure App Service' },
      { iconKey: 'azure', defaultLabel: 'Azure API Management' },
      { iconKey: 'azure', defaultLabel: 'Azure SQL' },
      { iconKey: 'azure', defaultLabel: 'Azure Cosmos DB' },
      { iconKey: 'azure', defaultLabel: 'Azure Storage' },
      { iconKey: 'azure', defaultLabel: 'Azure Key Vault' },
      { iconKey: 'azure', defaultLabel: 'Azure Service Bus' },
      { iconKey: 'azure', defaultLabel: 'Azure Event Hubs' },
      { iconKey: 'azure', defaultLabel: 'Azure Monitor' },
      { iconKey: 'azure', defaultLabel: 'Azure Container Apps' },
    ],
  },
  {
    title: 'Cloud providers',
    items: [
      { iconKey: 'googlecloud', defaultLabel: 'Google Cloud' },
      { iconKey: 'cloudflare', defaultLabel: 'Cloudflare' },
      { iconKey: 'digitalocean', defaultLabel: 'DigitalOcean' },
      { iconKey: 'hetzner', defaultLabel: 'Hetzner' },
      { iconKey: 'scaleway', defaultLabel: 'Scaleway' },
      { iconKey: 'vercel', defaultLabel: 'Vercel' },
    ],
  },
  {
    title: 'Data & messaging',
    items: [
      { iconKey: 'postgresql', defaultLabel: 'PostgreSQL' },
      { iconKey: 'redis', defaultLabel: 'Redis' },
      { iconKey: 'mongodb', defaultLabel: 'MongoDB' },
      { iconKey: 'rabbitmq', defaultLabel: 'RabbitMQ' },
      { iconKey: 'kafka', defaultLabel: 'Kafka' },
      { iconKey: 'nginx', defaultLabel: 'NGINX' },
    ],
  },
  {
    title: 'Observability',
    items: [
      { iconKey: 'grafana', defaultLabel: 'Grafana' },
      { iconKey: 'prometheus', defaultLabel: 'Prometheus' },
    ],
  },
  {
    title: 'Generic',
    items: [
      { iconKey: 'service', defaultLabel: 'Service' },
      { iconKey: 'api', defaultLabel: 'REST / API' },
      { iconKey: 'queue', defaultLabel: 'Queue / worker' },
    ],
  },
];
